# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Units(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Units()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnits(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def UnitsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x75\x6E\x30\x30", size_prefixed=size_prefixed)

    # Units
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Units
    def SourceName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Units
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Units
    def Units(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UnitsStart(builder):
    builder.StartObject(3)

def Start(builder):
    UnitsStart(builder)

def UnitsAddSourceName(builder, sourceName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sourceName), 0)

def AddSourceName(builder, sourceName):
    UnitsAddSourceName(builder, sourceName)

def UnitsAddTimestamp(builder, timestamp):
    builder.PrependInt64Slot(1, timestamp, 0)

def AddTimestamp(builder, timestamp):
    UnitsAddTimestamp(builder, timestamp)

def UnitsAddUnits(builder, units):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(units), 0)

def AddUnits(builder, units):
    UnitsAddUnits(builder, units)

def UnitsEnd(builder):
    return builder.EndObject()

def End(builder):
    return UnitsEnd(builder)
