# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Vetoes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Vetoes()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVetoes(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def VetoesBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x76\x63\x30\x30", size_prefixed=size_prefixed)

    # Vetoes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vetoes
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Vetoes
    def Vetoes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Vetoes
    def VetoNames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Vetoes
    def VetoNamesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Vetoes
    def VetoNamesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def VetoesStart(builder):
    builder.StartObject(3)

def Start(builder):
    VetoesStart(builder)

def VetoesAddTimestamp(builder, timestamp):
    builder.PrependInt64Slot(0, timestamp, 0)

def AddTimestamp(builder, timestamp):
    VetoesAddTimestamp(builder, timestamp)

def VetoesAddVetoes(builder, vetoes):
    builder.PrependUint32Slot(1, vetoes, 0)

def AddVetoes(builder, vetoes):
    VetoesAddVetoes(builder, vetoes)

def VetoesAddVetoNames(builder, vetoNames):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(vetoNames), 0)

def AddVetoNames(builder, vetoNames):
    VetoesAddVetoNames(builder, vetoNames)

def VetoesStartVetoNamesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVetoNamesVector(builder, numElems):
    return VetoesStartVetoNamesVector(builder, numElems)

def VetoesCreateVetoNamesVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateVetoNamesVector(builder, data):
    VetoesCreateVetoNamesVector(builder, data)

def VetoesEnd(builder):
    return builder.EndObject()

def End(builder):
    return VetoesEnd(builder)
