# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Pu00Message(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Pu00Message()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPu00Message(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def Pu00MessageBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x70\x75\x30\x30", size_prefixed=size_prefixed)

    # Pu00Message
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Pu00Message
    def SourceName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Pu00Message
    def MessageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Pu00Message
    def ReferenceTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Pu00Message
    def Vetos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return None

    # Pu00Message
    def PeriodNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return None

    # Pu00Message
    def ProtonCharge(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

def Pu00MessageStart(builder):
    builder.StartObject(6)

def Start(builder):
    Pu00MessageStart(builder)

def Pu00MessageAddSourceName(builder, sourceName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sourceName), 0)

def AddSourceName(builder, sourceName):
    Pu00MessageAddSourceName(builder, sourceName)

def Pu00MessageAddMessageId(builder, messageId):
    builder.PrependInt64Slot(1, messageId, 0)

def AddMessageId(builder, messageId):
    Pu00MessageAddMessageId(builder, messageId)

def Pu00MessageAddReferenceTime(builder, referenceTime):
    builder.PrependInt64Slot(2, referenceTime, 0)

def AddReferenceTime(builder, referenceTime):
    Pu00MessageAddReferenceTime(builder, referenceTime)

def Pu00MessageAddVetos(builder, vetos):
    builder.PrependUint32Slot(3, vetos, None)

def AddVetos(builder, vetos):
    Pu00MessageAddVetos(builder, vetos)

def Pu00MessageAddPeriodNumber(builder, periodNumber):
    builder.PrependUint32Slot(4, periodNumber, None)

def AddPeriodNumber(builder, periodNumber):
    Pu00MessageAddPeriodNumber(builder, periodNumber)

def Pu00MessageAddProtonCharge(builder, protonCharge):
    builder.PrependFloat32Slot(5, protonCharge, None)

def AddProtonCharge(builder, protonCharge):
    Pu00MessageAddProtonCharge(builder, protonCharge)

def Pu00MessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return Pu00MessageEnd(builder)
