// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_DTYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_DTYPE: i8 = 10;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_DTYPE: [DType; 11] = [
  DType::int8,
  DType::uint8,
  DType::int16,
  DType::uint16,
  DType::int32,
  DType::uint32,
  DType::int64,
  DType::uint64,
  DType::float32,
  DType::float64,
  DType::c_string,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct DType(pub i8);
#[allow(non_upper_case_globals)]
impl DType {
  pub const int8: Self = Self(0);
  pub const uint8: Self = Self(1);
  pub const int16: Self = Self(2);
  pub const uint16: Self = Self(3);
  pub const int32: Self = Self(4);
  pub const uint32: Self = Self(5);
  pub const int64: Self = Self(6);
  pub const uint64: Self = Self(7);
  pub const float32: Self = Self(8);
  pub const float64: Self = Self(9);
  pub const c_string: Self = Self(10);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 10;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::int8,
    Self::uint8,
    Self::int16,
    Self::uint16,
    Self::int32,
    Self::uint32,
    Self::int64,
    Self::uint64,
    Self::float32,
    Self::float64,
    Self::c_string,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::int8 => Some("int8"),
      Self::uint8 => Some("uint8"),
      Self::int16 => Some("int16"),
      Self::uint16 => Some("uint16"),
      Self::int32 => Some("int32"),
      Self::uint32 => Some("uint32"),
      Self::int64 => Some("int64"),
      Self::uint64 => Some("uint64"),
      Self::float32 => Some("float32"),
      Self::float64 => Some("float64"),
      Self::c_string => Some("c_string"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for DType {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for DType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for DType {
    type Output = DType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for DType {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for DType {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for DType {}
pub enum AttributeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Attribute<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Attribute<'a> {
  type Inner = Attribute<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Attribute<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_DESCRIPTION: ::flatbuffers::VOffsetT = 6;
  pub const VT_SOURCE: ::flatbuffers::VOffsetT = 8;
  pub const VT_DATA_TYPE: ::flatbuffers::VOffsetT = 10;
  pub const VT_DATA: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Attribute { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AttributeArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Attribute<'bldr>> {
    let mut builder = AttributeBuilder::new(_fbb);
    if let Some(x) = args.data { builder.add_data(x); }
    if let Some(x) = args.source { builder.add_source(x); }
    if let Some(x) = args.description { builder.add_description(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_data_type(args.data_type);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Attribute::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn description(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Attribute::VT_DESCRIPTION, None)}
  }
  #[inline]
  pub fn source(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Attribute::VT_SOURCE, None)}
  }
  #[inline]
  pub fn data_type(&self) -> DType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<DType>(Attribute::VT_DATA_TYPE, Some(DType::int8)).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Attribute::VT_DATA, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Attribute<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("description", Self::VT_DESCRIPTION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("source", Self::VT_SOURCE, false)?
     .visit_field::<DType>("data_type", Self::VT_DATA_TYPE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, true)?
     .finish();
    Ok(())
  }
}
pub struct AttributeArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub description: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub source: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub data_type: DType,
    pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for AttributeArgs<'a> {
  #[inline]
  fn default() -> Self {
    AttributeArgs {
      name: None, // required field
      description: None,
      source: None,
      data_type: DType::int8,
      data: None, // required field
    }
  }
}

pub struct AttributeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AttributeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Attribute::VT_NAME, name);
  }
  #[inline]
  pub fn add_description(&mut self, description: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Attribute::VT_DESCRIPTION, description);
  }
  #[inline]
  pub fn add_source(&mut self, source: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Attribute::VT_SOURCE, source);
  }
  #[inline]
  pub fn add_data_type(&mut self, data_type: DType) {
    self.fbb_.push_slot::<DType>(Attribute::VT_DATA_TYPE, data_type, DType::int8);
  }
  #[inline]
  pub fn add_data(&mut self, data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Attribute::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AttributeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AttributeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Attribute<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Attribute::VT_NAME,"name");
    self.fbb_.required(o, Attribute::VT_DATA,"data");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Attribute<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Attribute");
      ds.field("name", &self.name());
      ds.field("description", &self.description());
      ds.field("source", &self.source());
      ds.field("data_type", &self.data_type());
      ds.field("data", &self.data());
      ds.finish()
  }
}
pub enum ad00_ADArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ad00_ADArray<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ad00_ADArray<'a> {
  type Inner = ad00_ADArray<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ad00_ADArray<'a> {
  pub const VT_SOURCE_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_TIMESTAMP: ::flatbuffers::VOffsetT = 8;
  pub const VT_DIMENSIONS: ::flatbuffers::VOffsetT = 10;
  pub const VT_DATA_TYPE: ::flatbuffers::VOffsetT = 12;
  pub const VT_DATA: ::flatbuffers::VOffsetT = 14;
  pub const VT_ATTRIBUTES: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ad00_ADArray { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ad00_ADArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ad00_ADArray<'bldr>> {
    let mut builder = ad00_ADArrayBuilder::new(_fbb);
    builder.add_timestamp(args.timestamp);
    if let Some(x) = args.attributes { builder.add_attributes(x); }
    if let Some(x) = args.data { builder.add_data(x); }
    if let Some(x) = args.dimensions { builder.add_dimensions(x); }
    builder.add_id(args.id);
    if let Some(x) = args.source_name { builder.add_source_name(x); }
    builder.add_data_type(args.data_type);
    builder.finish()
  }


  #[inline]
  pub fn source_name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ad00_ADArray::VT_SOURCE_NAME, None).unwrap()}
  }
  #[inline]
  pub fn id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(ad00_ADArray::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn timestamp(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(ad00_ADArray::VT_TIMESTAMP, Some(0)).unwrap()}
  }
  #[inline]
  pub fn dimensions(&self) -> ::flatbuffers::Vector<'a, i64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i64>>>(ad00_ADArray::VT_DIMENSIONS, None).unwrap()}
  }
  #[inline]
  pub fn data_type(&self) -> DType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<DType>(ad00_ADArray::VT_DATA_TYPE, Some(DType::int8)).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(ad00_ADArray::VT_DATA, None).unwrap()}
  }
  #[inline]
  pub fn attributes(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Attribute<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Attribute>>>>(ad00_ADArray::VT_ATTRIBUTES, None)}
  }
}

impl ::flatbuffers::Verifiable for ad00_ADArray<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("source_name", Self::VT_SOURCE_NAME, true)?
     .visit_field::<i32>("id", Self::VT_ID, false)?
     .visit_field::<i64>("timestamp", Self::VT_TIMESTAMP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i64>>>("dimensions", Self::VT_DIMENSIONS, true)?
     .visit_field::<DType>("data_type", Self::VT_DATA_TYPE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Attribute>>>>("attributes", Self::VT_ATTRIBUTES, false)?
     .finish();
    Ok(())
  }
}
pub struct ad00_ADArrayArgs<'a> {
    pub source_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub id: i32,
    pub timestamp: i64,
    pub dimensions: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i64>>>,
    pub data_type: DType,
    pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub attributes: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Attribute<'a>>>>>,
}
impl<'a> Default for ad00_ADArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    ad00_ADArrayArgs {
      source_name: None, // required field
      id: 0,
      timestamp: 0,
      dimensions: None, // required field
      data_type: DType::int8,
      data: None, // required field
      attributes: None,
    }
  }
}

pub struct ad00_ADArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ad00_ADArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_source_name(&mut self, source_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ad00_ADArray::VT_SOURCE_NAME, source_name);
  }
  #[inline]
  pub fn add_id(&mut self, id: i32) {
    self.fbb_.push_slot::<i32>(ad00_ADArray::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: i64) {
    self.fbb_.push_slot::<i64>(ad00_ADArray::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn add_dimensions(&mut self, dimensions: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ad00_ADArray::VT_DIMENSIONS, dimensions);
  }
  #[inline]
  pub fn add_data_type(&mut self, data_type: DType) {
    self.fbb_.push_slot::<DType>(ad00_ADArray::VT_DATA_TYPE, data_type, DType::int8);
  }
  #[inline]
  pub fn add_data(&mut self, data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ad00_ADArray::VT_DATA, data);
  }
  #[inline]
  pub fn add_attributes(&mut self, attributes: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Attribute<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ad00_ADArray::VT_ATTRIBUTES, attributes);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ad00_ADArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ad00_ADArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ad00_ADArray<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, ad00_ADArray::VT_SOURCE_NAME,"source_name");
    self.fbb_.required(o, ad00_ADArray::VT_DIMENSIONS,"dimensions");
    self.fbb_.required(o, ad00_ADArray::VT_DATA,"data");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ad00_ADArray<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ad00_ADArray");
      ds.field("source_name", &self.source_name());
      ds.field("id", &self.id());
      ds.field("timestamp", &self.timestamp());
      ds.field("dimensions", &self.dimensions());
      ds.field("data_type", &self.data_type());
      ds.field("data", &self.data());
      ds.field("attributes", &self.attributes());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `ad00_ADArray`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_ad_00_adarray_unchecked`.
pub fn root_as_ad_00_adarray(buf: &[u8]) -> Result<ad00_ADArray<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<ad00_ADArray>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ad00_ADArray` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_ad_00_adarray_unchecked`.
pub fn size_prefixed_root_as_ad_00_adarray(buf: &[u8]) -> Result<ad00_ADArray<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<ad00_ADArray>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ad00_ADArray` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_ad_00_adarray_unchecked`.
pub fn root_as_ad_00_adarray_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ad00_ADArray<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<ad00_ADArray<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ad00_ADArray` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_ad_00_adarray_unchecked`.
pub fn size_prefixed_root_as_ad_00_adarray_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ad00_ADArray<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<ad00_ADArray<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ad00_ADArray and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ad00_ADArray`.
pub unsafe fn root_as_ad_00_adarray_unchecked(buf: &[u8]) -> ad00_ADArray<'_> {
  unsafe { ::flatbuffers::root_unchecked::<ad00_ADArray>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ad00_ADArray and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ad00_ADArray`.
pub unsafe fn size_prefixed_root_as_ad_00_adarray_unchecked(buf: &[u8]) -> ad00_ADArray<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<ad00_ADArray>(buf) }
}
pub const AD_00_ADARRAY_IDENTIFIER: &str = "ad00";

#[inline]
pub fn ad_00_adarray_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, AD_00_ADARRAY_IDENTIFIER, false)
}

#[inline]
pub fn ad_00_adarray_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, AD_00_ADARRAY_IDENTIFIER, true)
}

#[inline]
pub fn finish_ad_00_adarray_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<ad00_ADArray<'a>>) {
  fbb.finish(root, Some(AD_00_ADARRAY_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_ad_00_adarray_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<ad00_ADArray<'a>>) {
  fbb.finish_size_prefixed(root, Some(AD_00_ADARRAY_IDENTIFIER));
}
