// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ACTION_TYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ACTION_TYPE: i8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ACTION_TYPE: [ActionType; 2] = [
  ActionType::StartJob,
  ActionType::SetStopTime,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ActionType(pub i8);
#[allow(non_upper_case_globals)]
impl ActionType {
  pub const StartJob: Self = Self(0);
  pub const SetStopTime: Self = Self(1);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::StartJob,
    Self::SetStopTime,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::StartJob => Some("StartJob"),
      Self::SetStopTime => Some("SetStopTime"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for ActionType {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for ActionType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for ActionType {
    type Output = ActionType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for ActionType {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for ActionType {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for ActionType {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ACTION_OUTCOME: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ACTION_OUTCOME: i8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ACTION_OUTCOME: [ActionOutcome; 2] = [
  ActionOutcome::Success,
  ActionOutcome::Failure,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ActionOutcome(pub i8);
#[allow(non_upper_case_globals)]
impl ActionOutcome {
  pub const Success: Self = Self(0);
  pub const Failure: Self = Self(1);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Success,
    Self::Failure,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Success => Some("Success"),
      Self::Failure => Some("Failure"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for ActionOutcome {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for ActionOutcome {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for ActionOutcome {
    type Output = ActionOutcome;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for ActionOutcome {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for ActionOutcome {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for ActionOutcome {}
pub enum ActionResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ActionResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ActionResponse<'a> {
  type Inner = ActionResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ActionResponse<'a> {
  pub const VT_SERVICE_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_JOB_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_ACTION: ::flatbuffers::VOffsetT = 8;
  pub const VT_OUTCOME: ::flatbuffers::VOffsetT = 10;
  pub const VT_STATUS_CODE: ::flatbuffers::VOffsetT = 12;
  pub const VT_STOP_TIME: ::flatbuffers::VOffsetT = 14;
  pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 16;
  pub const VT_COMMAND_ID: ::flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ActionResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ActionResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ActionResponse<'bldr>> {
    let mut builder = ActionResponseBuilder::new(_fbb);
    builder.add_stop_time(args.stop_time);
    if let Some(x) = args.command_id { builder.add_command_id(x); }
    if let Some(x) = args.message { builder.add_message(x); }
    builder.add_status_code(args.status_code);
    if let Some(x) = args.job_id { builder.add_job_id(x); }
    if let Some(x) = args.service_id { builder.add_service_id(x); }
    builder.add_outcome(args.outcome);
    builder.add_action(args.action);
    builder.finish()
  }


  #[inline]
  pub fn service_id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ActionResponse::VT_SERVICE_ID, None).unwrap()}
  }
  #[inline]
  pub fn job_id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ActionResponse::VT_JOB_ID, None).unwrap()}
  }
  #[inline]
  pub fn action(&self) -> ActionType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ActionType>(ActionResponse::VT_ACTION, Some(ActionType::StartJob)).unwrap()}
  }
  #[inline]
  pub fn outcome(&self) -> ActionOutcome {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ActionOutcome>(ActionResponse::VT_OUTCOME, Some(ActionOutcome::Success)).unwrap()}
  }
  #[inline]
  pub fn status_code(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(ActionResponse::VT_STATUS_CODE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn stop_time(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ActionResponse::VT_STOP_TIME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ActionResponse::VT_MESSAGE, None)}
  }
  #[inline]
  pub fn command_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ActionResponse::VT_COMMAND_ID, None)}
  }
}

impl ::flatbuffers::Verifiable for ActionResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("service_id", Self::VT_SERVICE_ID, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("job_id", Self::VT_JOB_ID, true)?
     .visit_field::<ActionType>("action", Self::VT_ACTION, false)?
     .visit_field::<ActionOutcome>("outcome", Self::VT_OUTCOME, false)?
     .visit_field::<i32>("status_code", Self::VT_STATUS_CODE, false)?
     .visit_field::<u64>("stop_time", Self::VT_STOP_TIME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("command_id", Self::VT_COMMAND_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct ActionResponseArgs<'a> {
    pub service_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub job_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub action: ActionType,
    pub outcome: ActionOutcome,
    pub status_code: i32,
    pub stop_time: u64,
    pub message: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub command_id: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ActionResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    ActionResponseArgs {
      service_id: None, // required field
      job_id: None, // required field
      action: ActionType::StartJob,
      outcome: ActionOutcome::Success,
      status_code: 0,
      stop_time: 0,
      message: None,
      command_id: None,
    }
  }
}

pub struct ActionResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ActionResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_service_id(&mut self, service_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ActionResponse::VT_SERVICE_ID, service_id);
  }
  #[inline]
  pub fn add_job_id(&mut self, job_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ActionResponse::VT_JOB_ID, job_id);
  }
  #[inline]
  pub fn add_action(&mut self, action: ActionType) {
    self.fbb_.push_slot::<ActionType>(ActionResponse::VT_ACTION, action, ActionType::StartJob);
  }
  #[inline]
  pub fn add_outcome(&mut self, outcome: ActionOutcome) {
    self.fbb_.push_slot::<ActionOutcome>(ActionResponse::VT_OUTCOME, outcome, ActionOutcome::Success);
  }
  #[inline]
  pub fn add_status_code(&mut self, status_code: i32) {
    self.fbb_.push_slot::<i32>(ActionResponse::VT_STATUS_CODE, status_code, 0);
  }
  #[inline]
  pub fn add_stop_time(&mut self, stop_time: u64) {
    self.fbb_.push_slot::<u64>(ActionResponse::VT_STOP_TIME, stop_time, 0);
  }
  #[inline]
  pub fn add_message(&mut self, message: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ActionResponse::VT_MESSAGE, message);
  }
  #[inline]
  pub fn add_command_id(&mut self, command_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ActionResponse::VT_COMMAND_ID, command_id);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ActionResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ActionResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ActionResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, ActionResponse::VT_SERVICE_ID,"service_id");
    self.fbb_.required(o, ActionResponse::VT_JOB_ID,"job_id");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ActionResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ActionResponse");
      ds.field("service_id", &self.service_id());
      ds.field("job_id", &self.job_id());
      ds.field("action", &self.action());
      ds.field("outcome", &self.outcome());
      ds.field("status_code", &self.status_code());
      ds.field("stop_time", &self.stop_time());
      ds.field("message", &self.message());
      ds.field("command_id", &self.command_id());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `ActionResponse`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_action_response_unchecked`.
pub fn root_as_action_response(buf: &[u8]) -> Result<ActionResponse<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<ActionResponse>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ActionResponse` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_action_response_unchecked`.
pub fn size_prefixed_root_as_action_response(buf: &[u8]) -> Result<ActionResponse<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<ActionResponse>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ActionResponse` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_action_response_unchecked`.
pub fn root_as_action_response_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ActionResponse<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<ActionResponse<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ActionResponse` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_action_response_unchecked`.
pub fn size_prefixed_root_as_action_response_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ActionResponse<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<ActionResponse<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ActionResponse and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ActionResponse`.
pub unsafe fn root_as_action_response_unchecked(buf: &[u8]) -> ActionResponse<'_> {
  unsafe { ::flatbuffers::root_unchecked::<ActionResponse>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ActionResponse and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ActionResponse`.
pub unsafe fn size_prefixed_root_as_action_response_unchecked(buf: &[u8]) -> ActionResponse<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<ActionResponse>(buf) }
}
pub const ACTION_RESPONSE_IDENTIFIER: &str = "answ";

#[inline]
pub fn action_response_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, ACTION_RESPONSE_IDENTIFIER, false)
}

#[inline]
pub fn action_response_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, ACTION_RESPONSE_IDENTIFIER, true)
}

#[inline]
pub fn finish_action_response_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<ActionResponse<'a>>) {
  fbb.finish(root, Some(ACTION_RESPONSE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_action_response_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<ActionResponse<'a>>) {
  fbb.finish_size_prefixed(root, Some(ACTION_RESPONSE_IDENTIFIER));
}
