// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_DA_00_DTYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_DA_00_DTYPE: i8 = 11;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_DA_00_DTYPE: [da00_dtype; 12] = [
  da00_dtype::none,
  da00_dtype::int8,
  da00_dtype::uint8,
  da00_dtype::int16,
  da00_dtype::uint16,
  da00_dtype::int32,
  da00_dtype::uint32,
  da00_dtype::int64,
  da00_dtype::uint64,
  da00_dtype::float32,
  da00_dtype::float64,
  da00_dtype::c_string,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct da00_dtype(pub i8);
#[allow(non_upper_case_globals)]
impl da00_dtype {
  pub const none: Self = Self(0);
  pub const int8: Self = Self(1);
  pub const uint8: Self = Self(2);
  pub const int16: Self = Self(3);
  pub const uint16: Self = Self(4);
  pub const int32: Self = Self(5);
  pub const uint32: Self = Self(6);
  pub const int64: Self = Self(7);
  pub const uint64: Self = Self(8);
  pub const float32: Self = Self(9);
  pub const float64: Self = Self(10);
  pub const c_string: Self = Self(11);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 11;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::none,
    Self::int8,
    Self::uint8,
    Self::int16,
    Self::uint16,
    Self::int32,
    Self::uint32,
    Self::int64,
    Self::uint64,
    Self::float32,
    Self::float64,
    Self::c_string,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::none => Some("none"),
      Self::int8 => Some("int8"),
      Self::uint8 => Some("uint8"),
      Self::int16 => Some("int16"),
      Self::uint16 => Some("uint16"),
      Self::int32 => Some("int32"),
      Self::uint32 => Some("uint32"),
      Self::int64 => Some("int64"),
      Self::uint64 => Some("uint64"),
      Self::float32 => Some("float32"),
      Self::float64 => Some("float64"),
      Self::c_string => Some("c_string"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for da00_dtype {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for da00_dtype {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for da00_dtype {
    type Output = da00_dtype;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for da00_dtype {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for da00_dtype {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for da00_dtype {}
pub enum da00_VariableOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct da00_Variable<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for da00_Variable<'a> {
  type Inner = da00_Variable<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> da00_Variable<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_UNIT: ::flatbuffers::VOffsetT = 6;
  pub const VT_LABEL: ::flatbuffers::VOffsetT = 8;
  pub const VT_SOURCE: ::flatbuffers::VOffsetT = 10;
  pub const VT_DATA_TYPE: ::flatbuffers::VOffsetT = 12;
  pub const VT_AXES: ::flatbuffers::VOffsetT = 14;
  pub const VT_SHAPE: ::flatbuffers::VOffsetT = 16;
  pub const VT_DATA: ::flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    da00_Variable { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args da00_VariableArgs<'args>
  ) -> ::flatbuffers::WIPOffset<da00_Variable<'bldr>> {
    let mut builder = da00_VariableBuilder::new(_fbb);
    if let Some(x) = args.data { builder.add_data(x); }
    if let Some(x) = args.shape { builder.add_shape(x); }
    if let Some(x) = args.axes { builder.add_axes(x); }
    if let Some(x) = args.source { builder.add_source(x); }
    if let Some(x) = args.label { builder.add_label(x); }
    if let Some(x) = args.unit { builder.add_unit(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_data_type(args.data_type);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(da00_Variable::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn unit(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(da00_Variable::VT_UNIT, None)}
  }
  #[inline]
  pub fn label(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(da00_Variable::VT_LABEL, None)}
  }
  #[inline]
  pub fn source(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(da00_Variable::VT_SOURCE, None)}
  }
  #[inline]
  pub fn data_type(&self) -> da00_dtype {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<da00_dtype>(da00_Variable::VT_DATA_TYPE, Some(da00_dtype::none)).unwrap()}
  }
  #[inline]
  pub fn axes(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(da00_Variable::VT_AXES, None)}
  }
  #[inline]
  pub fn shape(&self) -> ::flatbuffers::Vector<'a, i64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i64>>>(da00_Variable::VT_SHAPE, None).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(da00_Variable::VT_DATA, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for da00_Variable<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("unit", Self::VT_UNIT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("label", Self::VT_LABEL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("source", Self::VT_SOURCE, false)?
     .visit_field::<da00_dtype>("data_type", Self::VT_DATA_TYPE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("axes", Self::VT_AXES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i64>>>("shape", Self::VT_SHAPE, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, true)?
     .finish();
    Ok(())
  }
}
pub struct da00_VariableArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub unit: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub label: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub source: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub data_type: da00_dtype,
    pub axes: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub shape: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i64>>>,
    pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for da00_VariableArgs<'a> {
  #[inline]
  fn default() -> Self {
    da00_VariableArgs {
      name: None, // required field
      unit: None,
      label: None,
      source: None,
      data_type: da00_dtype::none,
      axes: None,
      shape: None, // required field
      data: None, // required field
    }
  }
}

pub struct da00_VariableBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> da00_VariableBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(da00_Variable::VT_NAME, name);
  }
  #[inline]
  pub fn add_unit(&mut self, unit: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(da00_Variable::VT_UNIT, unit);
  }
  #[inline]
  pub fn add_label(&mut self, label: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(da00_Variable::VT_LABEL, label);
  }
  #[inline]
  pub fn add_source(&mut self, source: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(da00_Variable::VT_SOURCE, source);
  }
  #[inline]
  pub fn add_data_type(&mut self, data_type: da00_dtype) {
    self.fbb_.push_slot::<da00_dtype>(da00_Variable::VT_DATA_TYPE, data_type, da00_dtype::none);
  }
  #[inline]
  pub fn add_axes(&mut self, axes: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(da00_Variable::VT_AXES, axes);
  }
  #[inline]
  pub fn add_shape(&mut self, shape: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(da00_Variable::VT_SHAPE, shape);
  }
  #[inline]
  pub fn add_data(&mut self, data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(da00_Variable::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> da00_VariableBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    da00_VariableBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<da00_Variable<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, da00_Variable::VT_NAME,"name");
    self.fbb_.required(o, da00_Variable::VT_SHAPE,"shape");
    self.fbb_.required(o, da00_Variable::VT_DATA,"data");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for da00_Variable<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("da00_Variable");
      ds.field("name", &self.name());
      ds.field("unit", &self.unit());
      ds.field("label", &self.label());
      ds.field("source", &self.source());
      ds.field("data_type", &self.data_type());
      ds.field("axes", &self.axes());
      ds.field("shape", &self.shape());
      ds.field("data", &self.data());
      ds.finish()
  }
}
pub enum da00_DataArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct da00_DataArray<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for da00_DataArray<'a> {
  type Inner = da00_DataArray<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> da00_DataArray<'a> {
  pub const VT_SOURCE_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_TIMESTAMP: ::flatbuffers::VOffsetT = 6;
  pub const VT_DATA: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    da00_DataArray { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args da00_DataArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<da00_DataArray<'bldr>> {
    let mut builder = da00_DataArrayBuilder::new(_fbb);
    builder.add_timestamp(args.timestamp);
    if let Some(x) = args.data { builder.add_data(x); }
    if let Some(x) = args.source_name { builder.add_source_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn source_name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(da00_DataArray::VT_SOURCE_NAME, None).unwrap()}
  }
  #[inline]
  pub fn timestamp(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(da00_DataArray::VT_TIMESTAMP, Some(0)).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<da00_Variable<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<da00_Variable>>>>(da00_DataArray::VT_DATA, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for da00_DataArray<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("source_name", Self::VT_SOURCE_NAME, true)?
     .visit_field::<i64>("timestamp", Self::VT_TIMESTAMP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<da00_Variable>>>>("data", Self::VT_DATA, true)?
     .finish();
    Ok(())
  }
}
pub struct da00_DataArrayArgs<'a> {
    pub source_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub timestamp: i64,
    pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<da00_Variable<'a>>>>>,
}
impl<'a> Default for da00_DataArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    da00_DataArrayArgs {
      source_name: None, // required field
      timestamp: 0,
      data: None, // required field
    }
  }
}

pub struct da00_DataArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> da00_DataArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_source_name(&mut self, source_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(da00_DataArray::VT_SOURCE_NAME, source_name);
  }
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: i64) {
    self.fbb_.push_slot::<i64>(da00_DataArray::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn add_data(&mut self, data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<da00_Variable<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(da00_DataArray::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> da00_DataArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    da00_DataArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<da00_DataArray<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, da00_DataArray::VT_SOURCE_NAME,"source_name");
    self.fbb_.required(o, da00_DataArray::VT_DATA,"data");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for da00_DataArray<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("da00_DataArray");
      ds.field("source_name", &self.source_name());
      ds.field("timestamp", &self.timestamp());
      ds.field("data", &self.data());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `da00_DataArray`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_da_00_data_array_unchecked`.
pub fn root_as_da_00_data_array(buf: &[u8]) -> Result<da00_DataArray<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<da00_DataArray>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `da00_DataArray` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_da_00_data_array_unchecked`.
pub fn size_prefixed_root_as_da_00_data_array(buf: &[u8]) -> Result<da00_DataArray<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<da00_DataArray>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `da00_DataArray` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_da_00_data_array_unchecked`.
pub fn root_as_da_00_data_array_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<da00_DataArray<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<da00_DataArray<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `da00_DataArray` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_da_00_data_array_unchecked`.
pub fn size_prefixed_root_as_da_00_data_array_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<da00_DataArray<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<da00_DataArray<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a da00_DataArray and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `da00_DataArray`.
pub unsafe fn root_as_da_00_data_array_unchecked(buf: &[u8]) -> da00_DataArray<'_> {
  unsafe { ::flatbuffers::root_unchecked::<da00_DataArray>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed da00_DataArray and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `da00_DataArray`.
pub unsafe fn size_prefixed_root_as_da_00_data_array_unchecked(buf: &[u8]) -> da00_DataArray<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<da00_DataArray>(buf) }
}
pub const DA_00_DATA_ARRAY_IDENTIFIER: &str = "da00";

#[inline]
pub fn da_00_data_array_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, DA_00_DATA_ARRAY_IDENTIFIER, false)
}

#[inline]
pub fn da_00_data_array_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, DA_00_DATA_ARRAY_IDENTIFIER, true)
}

#[inline]
pub fn finish_da_00_data_array_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<da00_DataArray<'a>>) {
  fbb.finish(root, Some(DA_00_DATA_ARRAY_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_da_00_data_array_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<da00_DataArray<'a>>) {
  fbb.finish_size_prefixed(root, Some(DA_00_DATA_ARRAY_IDENTIFIER));
}
