// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_UPDATE_TYPE: u16 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_UPDATE_TYPE: u16 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_UPDATE_TYPE: [UpdateType; 4] = [
  UpdateType::ADD,
  UpdateType::REMOVE,
  UpdateType::REMOVEALL,
  UpdateType::REPLACE,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct UpdateType(pub u16);
#[allow(non_upper_case_globals)]
impl UpdateType {
  pub const ADD: Self = Self(0);
  pub const REMOVE: Self = Self(1);
  pub const REMOVEALL: Self = Self(2);
  pub const REPLACE: Self = Self(3);

  pub const ENUM_MIN: u16 = 0;
  pub const ENUM_MAX: u16 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::ADD,
    Self::REMOVE,
    Self::REMOVEALL,
    Self::REPLACE,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::ADD => Some("ADD"),
      Self::REMOVE => Some("REMOVE"),
      Self::REMOVEALL => Some("REMOVEALL"),
      Self::REPLACE => Some("REPLACE"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for UpdateType {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for UpdateType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u16>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for UpdateType {
    type Output = UpdateType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u16>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for UpdateType {
  type Scalar = u16;
  #[inline]
  fn to_little_endian(self) -> u16 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u16) -> Self {
    let b = u16::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for UpdateType {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u16::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for UpdateType {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_PROTOCOL: u16 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_PROTOCOL: u16 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_PROTOCOL: [Protocol; 3] = [
  Protocol::PVA,
  Protocol::CA,
  Protocol::FAKE,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Protocol(pub u16);
#[allow(non_upper_case_globals)]
impl Protocol {
  pub const PVA: Self = Self(0);
  pub const CA: Self = Self(1);
  pub const FAKE: Self = Self(2);

  pub const ENUM_MIN: u16 = 0;
  pub const ENUM_MAX: u16 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::PVA,
    Self::CA,
    Self::FAKE,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::PVA => Some("PVA"),
      Self::CA => Some("CA"),
      Self::FAKE => Some("FAKE"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Protocol {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Protocol {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u16>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Protocol {
    type Output = Protocol;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u16>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Protocol {
  type Scalar = u16;
  #[inline]
  fn to_little_endian(self) -> u16 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u16) -> Self {
    let b = u16::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Protocol {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u16::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Protocol {}
pub enum StreamOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Stream<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Stream<'a> {
  type Inner = Stream<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Stream<'a> {
  pub const VT_CHANNEL: ::flatbuffers::VOffsetT = 4;
  pub const VT_SCHEMA: ::flatbuffers::VOffsetT = 6;
  pub const VT_TOPIC: ::flatbuffers::VOffsetT = 8;
  pub const VT_PROTOCOL: ::flatbuffers::VOffsetT = 10;
  pub const VT_PERIODIC: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Stream { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args StreamArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Stream<'bldr>> {
    let mut builder = StreamBuilder::new(_fbb);
    builder.add_periodic(args.periodic);
    if let Some(x) = args.topic { builder.add_topic(x); }
    if let Some(x) = args.schema { builder.add_schema(x); }
    if let Some(x) = args.channel { builder.add_channel(x); }
    builder.add_protocol(args.protocol);
    builder.finish()
  }


  #[inline]
  pub fn channel(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Stream::VT_CHANNEL, None)}
  }
  #[inline]
  pub fn schema(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Stream::VT_SCHEMA, None)}
  }
  #[inline]
  pub fn topic(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Stream::VT_TOPIC, None)}
  }
  #[inline]
  pub fn protocol(&self) -> Protocol {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Protocol>(Stream::VT_PROTOCOL, Some(Protocol::PVA)).unwrap()}
  }
  #[inline]
  pub fn periodic(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Stream::VT_PERIODIC, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Stream<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("channel", Self::VT_CHANNEL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("schema", Self::VT_SCHEMA, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("topic", Self::VT_TOPIC, false)?
     .visit_field::<Protocol>("protocol", Self::VT_PROTOCOL, false)?
     .visit_field::<i32>("periodic", Self::VT_PERIODIC, false)?
     .finish();
    Ok(())
  }
}
pub struct StreamArgs<'a> {
    pub channel: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub schema: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub topic: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub protocol: Protocol,
    pub periodic: i32,
}
impl<'a> Default for StreamArgs<'a> {
  #[inline]
  fn default() -> Self {
    StreamArgs {
      channel: None,
      schema: None,
      topic: None,
      protocol: Protocol::PVA,
      periodic: 0,
    }
  }
}

pub struct StreamBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> StreamBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_channel(&mut self, channel: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Stream::VT_CHANNEL, channel);
  }
  #[inline]
  pub fn add_schema(&mut self, schema: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Stream::VT_SCHEMA, schema);
  }
  #[inline]
  pub fn add_topic(&mut self, topic: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Stream::VT_TOPIC, topic);
  }
  #[inline]
  pub fn add_protocol(&mut self, protocol: Protocol) {
    self.fbb_.push_slot::<Protocol>(Stream::VT_PROTOCOL, protocol, Protocol::PVA);
  }
  #[inline]
  pub fn add_periodic(&mut self, periodic: i32) {
    self.fbb_.push_slot::<i32>(Stream::VT_PERIODIC, periodic, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> StreamBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    StreamBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Stream<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Stream<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Stream");
      ds.field("channel", &self.channel());
      ds.field("schema", &self.schema());
      ds.field("topic", &self.topic());
      ds.field("protocol", &self.protocol());
      ds.field("periodic", &self.periodic());
      ds.finish()
  }
}
pub enum fc00_ConfigUpdateOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct fc00_ConfigUpdate<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for fc00_ConfigUpdate<'a> {
  type Inner = fc00_ConfigUpdate<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> fc00_ConfigUpdate<'a> {
  pub const VT_CONFIG_CHANGE: ::flatbuffers::VOffsetT = 4;
  pub const VT_STREAMS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    fc00_ConfigUpdate { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args fc00_ConfigUpdateArgs<'args>
  ) -> ::flatbuffers::WIPOffset<fc00_ConfigUpdate<'bldr>> {
    let mut builder = fc00_ConfigUpdateBuilder::new(_fbb);
    if let Some(x) = args.streams { builder.add_streams(x); }
    builder.add_config_change(args.config_change);
    builder.finish()
  }


  #[inline]
  pub fn config_change(&self) -> UpdateType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<UpdateType>(fc00_ConfigUpdate::VT_CONFIG_CHANGE, Some(UpdateType::ADD)).unwrap()}
  }
  #[inline]
  pub fn streams(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Stream<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Stream>>>>(fc00_ConfigUpdate::VT_STREAMS, None)}
  }
}

impl ::flatbuffers::Verifiable for fc00_ConfigUpdate<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<UpdateType>("config_change", Self::VT_CONFIG_CHANGE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Stream>>>>("streams", Self::VT_STREAMS, false)?
     .finish();
    Ok(())
  }
}
pub struct fc00_ConfigUpdateArgs<'a> {
    pub config_change: UpdateType,
    pub streams: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Stream<'a>>>>>,
}
impl<'a> Default for fc00_ConfigUpdateArgs<'a> {
  #[inline]
  fn default() -> Self {
    fc00_ConfigUpdateArgs {
      config_change: UpdateType::ADD,
      streams: None,
    }
  }
}

pub struct fc00_ConfigUpdateBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> fc00_ConfigUpdateBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_config_change(&mut self, config_change: UpdateType) {
    self.fbb_.push_slot::<UpdateType>(fc00_ConfigUpdate::VT_CONFIG_CHANGE, config_change, UpdateType::ADD);
  }
  #[inline]
  pub fn add_streams(&mut self, streams: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Stream<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(fc00_ConfigUpdate::VT_STREAMS, streams);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> fc00_ConfigUpdateBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    fc00_ConfigUpdateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<fc00_ConfigUpdate<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for fc00_ConfigUpdate<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("fc00_ConfigUpdate");
      ds.field("config_change", &self.config_change());
      ds.field("streams", &self.streams());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `fc00_ConfigUpdate`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_fc_00_config_update_unchecked`.
pub fn root_as_fc_00_config_update(buf: &[u8]) -> Result<fc00_ConfigUpdate<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<fc00_ConfigUpdate>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `fc00_ConfigUpdate` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_fc_00_config_update_unchecked`.
pub fn size_prefixed_root_as_fc_00_config_update(buf: &[u8]) -> Result<fc00_ConfigUpdate<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<fc00_ConfigUpdate>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `fc00_ConfigUpdate` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_fc_00_config_update_unchecked`.
pub fn root_as_fc_00_config_update_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<fc00_ConfigUpdate<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<fc00_ConfigUpdate<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `fc00_ConfigUpdate` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_fc_00_config_update_unchecked`.
pub fn size_prefixed_root_as_fc_00_config_update_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<fc00_ConfigUpdate<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<fc00_ConfigUpdate<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a fc00_ConfigUpdate and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `fc00_ConfigUpdate`.
pub unsafe fn root_as_fc_00_config_update_unchecked(buf: &[u8]) -> fc00_ConfigUpdate<'_> {
  unsafe { ::flatbuffers::root_unchecked::<fc00_ConfigUpdate>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed fc00_ConfigUpdate and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `fc00_ConfigUpdate`.
pub unsafe fn size_prefixed_root_as_fc_00_config_update_unchecked(buf: &[u8]) -> fc00_ConfigUpdate<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<fc00_ConfigUpdate>(buf) }
}
pub const FC_00_CONFIG_UPDATE_IDENTIFIER: &str = "fc00";

#[inline]
pub fn fc_00_config_update_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, FC_00_CONFIG_UPDATE_IDENTIFIER, false)
}

#[inline]
pub fn fc_00_config_update_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, FC_00_CONFIG_UPDATE_IDENTIFIER, true)
}

#[inline]
pub fn finish_fc_00_config_update_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<fc00_ConfigUpdate<'a>>) {
  fbb.finish(root, Some(FC_00_CONFIG_UPDATE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_fc_00_config_update_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<fc00_ConfigUpdate<'a>>) {
  fbb.finish_size_prefixed(root, Some(FC_00_CONFIG_UPDATE_IDENTIFIER));
}
