// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ARRAY: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ARRAY: u8 = 4;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ARRAY: [Array; 5] = [
  Array::NONE,
  Array::ArrayInt,
  Array::ArrayLong,
  Array::ArrayDouble,
  Array::ArrayFloat,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Array(pub u8);
#[allow(non_upper_case_globals)]
impl Array {
  pub const NONE: Self = Self(0);
  pub const ArrayInt: Self = Self(1);
  pub const ArrayLong: Self = Self(2);
  pub const ArrayDouble: Self = Self(3);
  pub const ArrayFloat: Self = Self(4);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 4;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::ArrayInt,
    Self::ArrayLong,
    Self::ArrayDouble,
    Self::ArrayFloat,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::ArrayInt => Some("ArrayInt"),
      Self::ArrayLong => Some("ArrayLong"),
      Self::ArrayDouble => Some("ArrayDouble"),
      Self::ArrayFloat => Some("ArrayFloat"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Array {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Array {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Array {
    type Output = Array;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Array {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Array {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Array {}
pub struct ArrayUnionTableOffset {}

pub enum ArrayIntOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ArrayInt<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ArrayInt<'a> {
  type Inner = ArrayInt<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ArrayInt<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ArrayInt { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ArrayIntArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ArrayInt<'bldr>> {
    let mut builder = ArrayIntBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> Option<::flatbuffers::Vector<'a, i32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i32>>>(ArrayInt::VT_VALUE, None)}
  }
}

impl ::flatbuffers::Verifiable for ArrayInt<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i32>>>("value", Self::VT_VALUE, false)?
     .finish();
    Ok(())
  }
}
pub struct ArrayIntArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i32>>>,
}
impl<'a> Default for ArrayIntArgs<'a> {
  #[inline]
  fn default() -> Self {
    ArrayIntArgs {
      value: None,
    }
  }
}

pub struct ArrayIntBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ArrayIntBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ArrayInt::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ArrayIntBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ArrayIntBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ArrayInt<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ArrayInt<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ArrayInt");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum ArrayLongOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ArrayLong<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ArrayLong<'a> {
  type Inner = ArrayLong<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ArrayLong<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ArrayLong { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ArrayLongArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ArrayLong<'bldr>> {
    let mut builder = ArrayLongBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> Option<::flatbuffers::Vector<'a, i64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i64>>>(ArrayLong::VT_VALUE, None)}
  }
}

impl ::flatbuffers::Verifiable for ArrayLong<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i64>>>("value", Self::VT_VALUE, false)?
     .finish();
    Ok(())
  }
}
pub struct ArrayLongArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i64>>>,
}
impl<'a> Default for ArrayLongArgs<'a> {
  #[inline]
  fn default() -> Self {
    ArrayLongArgs {
      value: None,
    }
  }
}

pub struct ArrayLongBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ArrayLongBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ArrayLong::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ArrayLongBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ArrayLongBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ArrayLong<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ArrayLong<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ArrayLong");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum ArrayDoubleOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ArrayDouble<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ArrayDouble<'a> {
  type Inner = ArrayDouble<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ArrayDouble<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ArrayDouble { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ArrayDoubleArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ArrayDouble<'bldr>> {
    let mut builder = ArrayDoubleBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> Option<::flatbuffers::Vector<'a, f64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f64>>>(ArrayDouble::VT_VALUE, None)}
  }
}

impl ::flatbuffers::Verifiable for ArrayDouble<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f64>>>("value", Self::VT_VALUE, false)?
     .finish();
    Ok(())
  }
}
pub struct ArrayDoubleArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f64>>>,
}
impl<'a> Default for ArrayDoubleArgs<'a> {
  #[inline]
  fn default() -> Self {
    ArrayDoubleArgs {
      value: None,
    }
  }
}

pub struct ArrayDoubleBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ArrayDoubleBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ArrayDouble::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ArrayDoubleBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ArrayDoubleBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ArrayDouble<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ArrayDouble<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ArrayDouble");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum ArrayFloatOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ArrayFloat<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ArrayFloat<'a> {
  type Inner = ArrayFloat<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ArrayFloat<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ArrayFloat { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ArrayFloatArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ArrayFloat<'bldr>> {
    let mut builder = ArrayFloatBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> Option<::flatbuffers::Vector<'a, f32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f32>>>(ArrayFloat::VT_VALUE, None)}
  }
}

impl ::flatbuffers::Verifiable for ArrayFloat<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f32>>>("value", Self::VT_VALUE, false)?
     .finish();
    Ok(())
  }
}
pub struct ArrayFloatArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f32>>>,
}
impl<'a> Default for ArrayFloatArgs<'a> {
  #[inline]
  fn default() -> Self {
    ArrayFloatArgs {
      value: None,
    }
  }
}

pub struct ArrayFloatBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ArrayFloatBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , f32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ArrayFloat::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ArrayFloatBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ArrayFloatBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ArrayFloat<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ArrayFloat<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ArrayFloat");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum DimensionMetaDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DimensionMetaData<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DimensionMetaData<'a> {
  type Inner = DimensionMetaData<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DimensionMetaData<'a> {
  pub const VT_LENGTH: ::flatbuffers::VOffsetT = 4;
  pub const VT_UNIT: ::flatbuffers::VOffsetT = 6;
  pub const VT_LABEL: ::flatbuffers::VOffsetT = 8;
  pub const VT_BIN_BOUNDARIES_TYPE: ::flatbuffers::VOffsetT = 10;
  pub const VT_BIN_BOUNDARIES: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DimensionMetaData { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DimensionMetaDataArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DimensionMetaData<'bldr>> {
    let mut builder = DimensionMetaDataBuilder::new(_fbb);
    if let Some(x) = args.bin_boundaries { builder.add_bin_boundaries(x); }
    if let Some(x) = args.label { builder.add_label(x); }
    if let Some(x) = args.unit { builder.add_unit(x); }
    builder.add_length(args.length);
    builder.add_bin_boundaries_type(args.bin_boundaries_type);
    builder.finish()
  }


  #[inline]
  pub fn length(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DimensionMetaData::VT_LENGTH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn unit(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DimensionMetaData::VT_UNIT, None)}
  }
  #[inline]
  pub fn label(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DimensionMetaData::VT_LABEL, None)}
  }
  #[inline]
  pub fn bin_boundaries_type(&self) -> Array {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Array>(DimensionMetaData::VT_BIN_BOUNDARIES_TYPE, Some(Array::NONE)).unwrap()}
  }
  #[inline]
  pub fn bin_boundaries(&self) -> Option<::flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(DimensionMetaData::VT_BIN_BOUNDARIES, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn bin_boundaries_as_array_int(&self) -> Option<ArrayInt<'a>> {
    if self.bin_boundaries_type() == Array::ArrayInt {
      self.bin_boundaries().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayInt::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn bin_boundaries_as_array_long(&self) -> Option<ArrayLong<'a>> {
    if self.bin_boundaries_type() == Array::ArrayLong {
      self.bin_boundaries().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayLong::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn bin_boundaries_as_array_double(&self) -> Option<ArrayDouble<'a>> {
    if self.bin_boundaries_type() == Array::ArrayDouble {
      self.bin_boundaries().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayDouble::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn bin_boundaries_as_array_float(&self) -> Option<ArrayFloat<'a>> {
    if self.bin_boundaries_type() == Array::ArrayFloat {
      self.bin_boundaries().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayFloat::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for DimensionMetaData<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<i32>("length", Self::VT_LENGTH, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("unit", Self::VT_UNIT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("label", Self::VT_LABEL, false)?
     .visit_union::<Array, _>("bin_boundaries_type", Self::VT_BIN_BOUNDARIES_TYPE, "bin_boundaries", Self::VT_BIN_BOUNDARIES, false, |key, v, pos| {
        match key {
          Array::ArrayInt => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayInt>>("Array::ArrayInt", pos),
          Array::ArrayLong => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayLong>>("Array::ArrayLong", pos),
          Array::ArrayDouble => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayDouble>>("Array::ArrayDouble", pos),
          Array::ArrayFloat => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayFloat>>("Array::ArrayFloat", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct DimensionMetaDataArgs<'a> {
    pub length: i32,
    pub unit: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub label: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub bin_boundaries_type: Array,
    pub bin_boundaries: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for DimensionMetaDataArgs<'a> {
  #[inline]
  fn default() -> Self {
    DimensionMetaDataArgs {
      length: 0,
      unit: None,
      label: None,
      bin_boundaries_type: Array::NONE,
      bin_boundaries: None,
    }
  }
}

pub struct DimensionMetaDataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DimensionMetaDataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_length(&mut self, length: i32) {
    self.fbb_.push_slot::<i32>(DimensionMetaData::VT_LENGTH, length, 0);
  }
  #[inline]
  pub fn add_unit(&mut self, unit: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DimensionMetaData::VT_UNIT, unit);
  }
  #[inline]
  pub fn add_label(&mut self, label: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DimensionMetaData::VT_LABEL, label);
  }
  #[inline]
  pub fn add_bin_boundaries_type(&mut self, bin_boundaries_type: Array) {
    self.fbb_.push_slot::<Array>(DimensionMetaData::VT_BIN_BOUNDARIES_TYPE, bin_boundaries_type, Array::NONE);
  }
  #[inline]
  pub fn add_bin_boundaries(&mut self, bin_boundaries: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DimensionMetaData::VT_BIN_BOUNDARIES, bin_boundaries);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DimensionMetaDataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DimensionMetaDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DimensionMetaData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DimensionMetaData<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DimensionMetaData");
      ds.field("length", &self.length());
      ds.field("unit", &self.unit());
      ds.field("label", &self.label());
      ds.field("bin_boundaries_type", &self.bin_boundaries_type());
      match self.bin_boundaries_type() {
        Array::ArrayInt => {
          if let Some(x) = self.bin_boundaries_as_array_int() {
            ds.field("bin_boundaries", &x)
          } else {
            ds.field("bin_boundaries", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Array::ArrayLong => {
          if let Some(x) = self.bin_boundaries_as_array_long() {
            ds.field("bin_boundaries", &x)
          } else {
            ds.field("bin_boundaries", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Array::ArrayDouble => {
          if let Some(x) = self.bin_boundaries_as_array_double() {
            ds.field("bin_boundaries", &x)
          } else {
            ds.field("bin_boundaries", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Array::ArrayFloat => {
          if let Some(x) = self.bin_boundaries_as_array_float() {
            ds.field("bin_boundaries", &x)
          } else {
            ds.field("bin_boundaries", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("bin_boundaries", &x)
        },
      };
      ds.finish()
  }
}
pub enum EventHistogramOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EventHistogram<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for EventHistogram<'a> {
  type Inner = EventHistogram<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> EventHistogram<'a> {
  pub const VT_SOURCE: ::flatbuffers::VOffsetT = 4;
  pub const VT_TIMESTAMP: ::flatbuffers::VOffsetT = 6;
  pub const VT_DIM_METADATA: ::flatbuffers::VOffsetT = 8;
  pub const VT_LAST_METADATA_TIMESTAMP: ::flatbuffers::VOffsetT = 10;
  pub const VT_CURRENT_SHAPE: ::flatbuffers::VOffsetT = 12;
  pub const VT_OFFSET: ::flatbuffers::VOffsetT = 14;
  pub const VT_DATA_TYPE: ::flatbuffers::VOffsetT = 16;
  pub const VT_DATA: ::flatbuffers::VOffsetT = 18;
  pub const VT_ERRORS_TYPE: ::flatbuffers::VOffsetT = 20;
  pub const VT_ERRORS: ::flatbuffers::VOffsetT = 22;
  pub const VT_INFO: ::flatbuffers::VOffsetT = 24;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    EventHistogram { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EventHistogramArgs<'args>
  ) -> ::flatbuffers::WIPOffset<EventHistogram<'bldr>> {
    let mut builder = EventHistogramBuilder::new(_fbb);
    builder.add_last_metadata_timestamp(args.last_metadata_timestamp);
    builder.add_timestamp(args.timestamp);
    if let Some(x) = args.info { builder.add_info(x); }
    if let Some(x) = args.errors { builder.add_errors(x); }
    if let Some(x) = args.data { builder.add_data(x); }
    if let Some(x) = args.offset { builder.add_offset(x); }
    if let Some(x) = args.current_shape { builder.add_current_shape(x); }
    if let Some(x) = args.dim_metadata { builder.add_dim_metadata(x); }
    if let Some(x) = args.source { builder.add_source(x); }
    builder.add_errors_type(args.errors_type);
    builder.add_data_type(args.data_type);
    builder.finish()
  }


  #[inline]
  pub fn source(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EventHistogram::VT_SOURCE, None)}
  }
  #[inline]
  pub fn timestamp(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(EventHistogram::VT_TIMESTAMP, Some(0)).unwrap()}
  }
  #[inline]
  pub fn dim_metadata(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DimensionMetaData<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DimensionMetaData>>>>(EventHistogram::VT_DIM_METADATA, None)}
  }
  #[inline]
  pub fn last_metadata_timestamp(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(EventHistogram::VT_LAST_METADATA_TIMESTAMP, Some(0)).unwrap()}
  }
  #[inline]
  pub fn current_shape(&self) -> ::flatbuffers::Vector<'a, i32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i32>>>(EventHistogram::VT_CURRENT_SHAPE, None).unwrap()}
  }
  #[inline]
  pub fn offset(&self) -> Option<::flatbuffers::Vector<'a, i32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i32>>>(EventHistogram::VT_OFFSET, None)}
  }
  #[inline]
  pub fn data_type(&self) -> Array {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Array>(EventHistogram::VT_DATA_TYPE, Some(Array::NONE)).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> Option<::flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(EventHistogram::VT_DATA, None)}
  }
  #[inline]
  pub fn errors_type(&self) -> Array {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Array>(EventHistogram::VT_ERRORS_TYPE, Some(Array::NONE)).unwrap()}
  }
  #[inline]
  pub fn errors(&self) -> Option<::flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(EventHistogram::VT_ERRORS, None)}
  }
  #[inline]
  pub fn info(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EventHistogram::VT_INFO, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_array_int(&self) -> Option<ArrayInt<'a>> {
    if self.data_type() == Array::ArrayInt {
      self.data().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayInt::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_array_long(&self) -> Option<ArrayLong<'a>> {
    if self.data_type() == Array::ArrayLong {
      self.data().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayLong::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_array_double(&self) -> Option<ArrayDouble<'a>> {
    if self.data_type() == Array::ArrayDouble {
      self.data().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayDouble::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_array_float(&self) -> Option<ArrayFloat<'a>> {
    if self.data_type() == Array::ArrayFloat {
      self.data().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayFloat::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn errors_as_array_int(&self) -> Option<ArrayInt<'a>> {
    if self.errors_type() == Array::ArrayInt {
      self.errors().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayInt::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn errors_as_array_long(&self) -> Option<ArrayLong<'a>> {
    if self.errors_type() == Array::ArrayLong {
      self.errors().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayLong::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn errors_as_array_double(&self) -> Option<ArrayDouble<'a>> {
    if self.errors_type() == Array::ArrayDouble {
      self.errors().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayDouble::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn errors_as_array_float(&self) -> Option<ArrayFloat<'a>> {
    if self.errors_type() == Array::ArrayFloat {
      self.errors().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ArrayFloat::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for EventHistogram<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("source", Self::VT_SOURCE, false)?
     .visit_field::<i64>("timestamp", Self::VT_TIMESTAMP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<DimensionMetaData>>>>("dim_metadata", Self::VT_DIM_METADATA, false)?
     .visit_field::<i64>("last_metadata_timestamp", Self::VT_LAST_METADATA_TIMESTAMP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i32>>>("current_shape", Self::VT_CURRENT_SHAPE, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i32>>>("offset", Self::VT_OFFSET, false)?
     .visit_union::<Array, _>("data_type", Self::VT_DATA_TYPE, "data", Self::VT_DATA, false, |key, v, pos| {
        match key {
          Array::ArrayInt => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayInt>>("Array::ArrayInt", pos),
          Array::ArrayLong => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayLong>>("Array::ArrayLong", pos),
          Array::ArrayDouble => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayDouble>>("Array::ArrayDouble", pos),
          Array::ArrayFloat => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayFloat>>("Array::ArrayFloat", pos),
          _ => Ok(()),
        }
     })?
     .visit_union::<Array, _>("errors_type", Self::VT_ERRORS_TYPE, "errors", Self::VT_ERRORS, false, |key, v, pos| {
        match key {
          Array::ArrayInt => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayInt>>("Array::ArrayInt", pos),
          Array::ArrayLong => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayLong>>("Array::ArrayLong", pos),
          Array::ArrayDouble => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayDouble>>("Array::ArrayDouble", pos),
          Array::ArrayFloat => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ArrayFloat>>("Array::ArrayFloat", pos),
          _ => Ok(()),
        }
     })?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("info", Self::VT_INFO, false)?
     .finish();
    Ok(())
  }
}
pub struct EventHistogramArgs<'a> {
    pub source: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub timestamp: i64,
    pub dim_metadata: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DimensionMetaData<'a>>>>>,
    pub last_metadata_timestamp: i64,
    pub current_shape: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i32>>>,
    pub offset: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i32>>>,
    pub data_type: Array,
    pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
    pub errors_type: Array,
    pub errors: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
    pub info: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for EventHistogramArgs<'a> {
  #[inline]
  fn default() -> Self {
    EventHistogramArgs {
      source: None,
      timestamp: 0,
      dim_metadata: None,
      last_metadata_timestamp: 0,
      current_shape: None, // required field
      offset: None,
      data_type: Array::NONE,
      data: None,
      errors_type: Array::NONE,
      errors: None,
      info: None,
    }
  }
}

pub struct EventHistogramBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EventHistogramBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_source(&mut self, source: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventHistogram::VT_SOURCE, source);
  }
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: i64) {
    self.fbb_.push_slot::<i64>(EventHistogram::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn add_dim_metadata(&mut self, dim_metadata: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<DimensionMetaData<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventHistogram::VT_DIM_METADATA, dim_metadata);
  }
  #[inline]
  pub fn add_last_metadata_timestamp(&mut self, last_metadata_timestamp: i64) {
    self.fbb_.push_slot::<i64>(EventHistogram::VT_LAST_METADATA_TIMESTAMP, last_metadata_timestamp, 0);
  }
  #[inline]
  pub fn add_current_shape(&mut self, current_shape: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventHistogram::VT_CURRENT_SHAPE, current_shape);
  }
  #[inline]
  pub fn add_offset(&mut self, offset: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventHistogram::VT_OFFSET, offset);
  }
  #[inline]
  pub fn add_data_type(&mut self, data_type: Array) {
    self.fbb_.push_slot::<Array>(EventHistogram::VT_DATA_TYPE, data_type, Array::NONE);
  }
  #[inline]
  pub fn add_data(&mut self, data: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventHistogram::VT_DATA, data);
  }
  #[inline]
  pub fn add_errors_type(&mut self, errors_type: Array) {
    self.fbb_.push_slot::<Array>(EventHistogram::VT_ERRORS_TYPE, errors_type, Array::NONE);
  }
  #[inline]
  pub fn add_errors(&mut self, errors: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventHistogram::VT_ERRORS, errors);
  }
  #[inline]
  pub fn add_info(&mut self, info: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EventHistogram::VT_INFO, info);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EventHistogramBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EventHistogramBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<EventHistogram<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, EventHistogram::VT_CURRENT_SHAPE,"current_shape");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for EventHistogram<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("EventHistogram");
      ds.field("source", &self.source());
      ds.field("timestamp", &self.timestamp());
      ds.field("dim_metadata", &self.dim_metadata());
      ds.field("last_metadata_timestamp", &self.last_metadata_timestamp());
      ds.field("current_shape", &self.current_shape());
      ds.field("offset", &self.offset());
      ds.field("data_type", &self.data_type());
      match self.data_type() {
        Array::ArrayInt => {
          if let Some(x) = self.data_as_array_int() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Array::ArrayLong => {
          if let Some(x) = self.data_as_array_long() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Array::ArrayDouble => {
          if let Some(x) = self.data_as_array_double() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Array::ArrayFloat => {
          if let Some(x) = self.data_as_array_float() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("data", &x)
        },
      };
      ds.field("errors_type", &self.errors_type());
      match self.errors_type() {
        Array::ArrayInt => {
          if let Some(x) = self.errors_as_array_int() {
            ds.field("errors", &x)
          } else {
            ds.field("errors", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Array::ArrayLong => {
          if let Some(x) = self.errors_as_array_long() {
            ds.field("errors", &x)
          } else {
            ds.field("errors", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Array::ArrayDouble => {
          if let Some(x) = self.errors_as_array_double() {
            ds.field("errors", &x)
          } else {
            ds.field("errors", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Array::ArrayFloat => {
          if let Some(x) = self.errors_as_array_float() {
            ds.field("errors", &x)
          } else {
            ds.field("errors", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("errors", &x)
        },
      };
      ds.field("info", &self.info());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `EventHistogram`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_event_histogram_unchecked`.
pub fn root_as_event_histogram(buf: &[u8]) -> Result<EventHistogram<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<EventHistogram>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `EventHistogram` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_event_histogram_unchecked`.
pub fn size_prefixed_root_as_event_histogram(buf: &[u8]) -> Result<EventHistogram<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<EventHistogram>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `EventHistogram` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_event_histogram_unchecked`.
pub fn root_as_event_histogram_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EventHistogram<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<EventHistogram<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `EventHistogram` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_event_histogram_unchecked`.
pub fn size_prefixed_root_as_event_histogram_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EventHistogram<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<EventHistogram<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a EventHistogram and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `EventHistogram`.
pub unsafe fn root_as_event_histogram_unchecked(buf: &[u8]) -> EventHistogram<'_> {
  unsafe { ::flatbuffers::root_unchecked::<EventHistogram>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed EventHistogram and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `EventHistogram`.
pub unsafe fn size_prefixed_root_as_event_histogram_unchecked(buf: &[u8]) -> EventHistogram<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<EventHistogram>(buf) }
}
pub const EVENT_HISTOGRAM_IDENTIFIER: &str = "hs01";

#[inline]
pub fn event_histogram_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, EVENT_HISTOGRAM_IDENTIFIER, false)
}

#[inline]
pub fn event_histogram_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, EVENT_HISTOGRAM_IDENTIFIER, true)
}

#[inline]
pub fn finish_event_histogram_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<EventHistogram<'a>>) {
  fbb.finish(root, Some(EVENT_HISTOGRAM_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_event_histogram_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<EventHistogram<'a>>) {
  fbb.finish_size_prefixed(root, Some(EVENT_HISTOGRAM_IDENTIFIER));
}
