// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

pub enum JsonDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct JsonData<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for JsonData<'a> {
  type Inner = JsonData<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> JsonData<'a> {
  pub const VT_JSON: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    JsonData { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args JsonDataArgs<'args>
  ) -> ::flatbuffers::WIPOffset<JsonData<'bldr>> {
    let mut builder = JsonDataBuilder::new(_fbb);
    if let Some(x) = args.json { builder.add_json(x); }
    builder.finish()
  }


  #[inline]
  pub fn json(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(JsonData::VT_JSON, None)}
  }
}

impl ::flatbuffers::Verifiable for JsonData<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("json", Self::VT_JSON, false)?
     .finish();
    Ok(())
  }
}
pub struct JsonDataArgs<'a> {
    pub json: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for JsonDataArgs<'a> {
  #[inline]
  fn default() -> Self {
    JsonDataArgs {
      json: None,
    }
  }
}

pub struct JsonDataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> JsonDataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_json(&mut self, json: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(JsonData::VT_JSON, json);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> JsonDataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    JsonDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<JsonData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for JsonData<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("JsonData");
      ds.field("json", &self.json());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `JsonData`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_json_data_unchecked`.
pub fn root_as_json_data(buf: &[u8]) -> Result<JsonData<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<JsonData>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `JsonData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_json_data_unchecked`.
pub fn size_prefixed_root_as_json_data(buf: &[u8]) -> Result<JsonData<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<JsonData>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `JsonData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_json_data_unchecked`.
pub fn root_as_json_data_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<JsonData<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<JsonData<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `JsonData` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_json_data_unchecked`.
pub fn size_prefixed_root_as_json_data_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<JsonData<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<JsonData<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a JsonData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `JsonData`.
pub unsafe fn root_as_json_data_unchecked(buf: &[u8]) -> JsonData<'_> {
  unsafe { ::flatbuffers::root_unchecked::<JsonData>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed JsonData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `JsonData`.
pub unsafe fn size_prefixed_root_as_json_data_unchecked(buf: &[u8]) -> JsonData<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<JsonData>(buf) }
}
pub const JSON_DATA_IDENTIFIER: &str = "json";

#[inline]
pub fn json_data_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, JSON_DATA_IDENTIFIER, false)
}

#[inline]
pub fn json_data_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, JSON_DATA_IDENTIFIER, true)
}

#[inline]
pub fn finish_json_data_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<JsonData<'a>>) {
  fbb.finish(root, Some(JSON_DATA_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_json_data_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<JsonData<'a>>) {
  fbb.finish_size_prefixed(root, Some(JSON_DATA_IDENTIFIER));
}
