// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

pub enum Pu00MessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Pu00Message<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Pu00Message<'a> {
  type Inner = Pu00Message<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Pu00Message<'a> {
  pub const VT_SOURCE_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_MESSAGE_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_REFERENCE_TIME: ::flatbuffers::VOffsetT = 8;
  pub const VT_VETOS: ::flatbuffers::VOffsetT = 10;
  pub const VT_PERIOD_NUMBER: ::flatbuffers::VOffsetT = 12;
  pub const VT_PROTON_CHARGE: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Pu00Message { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args Pu00MessageArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Pu00Message<'bldr>> {
    let mut builder = Pu00MessageBuilder::new(_fbb);
    builder.add_reference_time(args.reference_time);
    builder.add_message_id(args.message_id);
    if let Some(x) = args.proton_charge { builder.add_proton_charge(x); }
    if let Some(x) = args.period_number { builder.add_period_number(x); }
    if let Some(x) = args.vetos { builder.add_vetos(x); }
    if let Some(x) = args.source_name { builder.add_source_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn source_name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Pu00Message::VT_SOURCE_NAME, None).unwrap()}
  }
  #[inline]
  pub fn message_id(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Pu00Message::VT_MESSAGE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn reference_time(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Pu00Message::VT_REFERENCE_TIME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn vetos(&self) -> Option<u32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Pu00Message::VT_VETOS, None)}
  }
  #[inline]
  pub fn period_number(&self) -> Option<u32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Pu00Message::VT_PERIOD_NUMBER, None)}
  }
  #[inline]
  pub fn proton_charge(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Pu00Message::VT_PROTON_CHARGE, None)}
  }
}

impl ::flatbuffers::Verifiable for Pu00Message<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("source_name", Self::VT_SOURCE_NAME, true)?
     .visit_field::<i64>("message_id", Self::VT_MESSAGE_ID, false)?
     .visit_field::<i64>("reference_time", Self::VT_REFERENCE_TIME, false)?
     .visit_field::<u32>("vetos", Self::VT_VETOS, false)?
     .visit_field::<u32>("period_number", Self::VT_PERIOD_NUMBER, false)?
     .visit_field::<f32>("proton_charge", Self::VT_PROTON_CHARGE, false)?
     .finish();
    Ok(())
  }
}
pub struct Pu00MessageArgs<'a> {
    pub source_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub message_id: i64,
    pub reference_time: i64,
    pub vetos: Option<u32>,
    pub period_number: Option<u32>,
    pub proton_charge: Option<f32>,
}
impl<'a> Default for Pu00MessageArgs<'a> {
  #[inline]
  fn default() -> Self {
    Pu00MessageArgs {
      source_name: None, // required field
      message_id: 0,
      reference_time: 0,
      vetos: None,
      period_number: None,
      proton_charge: None,
    }
  }
}

pub struct Pu00MessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> Pu00MessageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_source_name(&mut self, source_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Pu00Message::VT_SOURCE_NAME, source_name);
  }
  #[inline]
  pub fn add_message_id(&mut self, message_id: i64) {
    self.fbb_.push_slot::<i64>(Pu00Message::VT_MESSAGE_ID, message_id, 0);
  }
  #[inline]
  pub fn add_reference_time(&mut self, reference_time: i64) {
    self.fbb_.push_slot::<i64>(Pu00Message::VT_REFERENCE_TIME, reference_time, 0);
  }
  #[inline]
  pub fn add_vetos(&mut self, vetos: u32) {
    self.fbb_.push_slot_always::<u32>(Pu00Message::VT_VETOS, vetos);
  }
  #[inline]
  pub fn add_period_number(&mut self, period_number: u32) {
    self.fbb_.push_slot_always::<u32>(Pu00Message::VT_PERIOD_NUMBER, period_number);
  }
  #[inline]
  pub fn add_proton_charge(&mut self, proton_charge: f32) {
    self.fbb_.push_slot_always::<f32>(Pu00Message::VT_PROTON_CHARGE, proton_charge);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> Pu00MessageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    Pu00MessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Pu00Message<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Pu00Message::VT_SOURCE_NAME,"source_name");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Pu00Message<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Pu00Message");
      ds.field("source_name", &self.source_name());
      ds.field("message_id", &self.message_id());
      ds.field("reference_time", &self.reference_time());
      ds.field("vetos", &self.vetos());
      ds.field("period_number", &self.period_number());
      ds.field("proton_charge", &self.proton_charge());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Pu00Message`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pu_00_message_unchecked`.
pub fn root_as_pu_00_message(buf: &[u8]) -> Result<Pu00Message<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Pu00Message>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Pu00Message` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_pu_00_message_unchecked`.
pub fn size_prefixed_root_as_pu_00_message(buf: &[u8]) -> Result<Pu00Message<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Pu00Message>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Pu00Message` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pu_00_message_unchecked`.
pub fn root_as_pu_00_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Pu00Message<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Pu00Message<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Pu00Message` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pu_00_message_unchecked`.
pub fn size_prefixed_root_as_pu_00_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Pu00Message<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Pu00Message<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Pu00Message and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Pu00Message`.
pub unsafe fn root_as_pu_00_message_unchecked(buf: &[u8]) -> Pu00Message<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Pu00Message>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Pu00Message and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Pu00Message`.
pub unsafe fn size_prefixed_root_as_pu_00_message_unchecked(buf: &[u8]) -> Pu00Message<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Pu00Message>(buf) }
}
pub const PU_00_MESSAGE_IDENTIFIER: &str = "pu00";

#[inline]
pub fn pu_00_message_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, PU_00_MESSAGE_IDENTIFIER, false)
}

#[inline]
pub fn pu_00_message_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, PU_00_MESSAGE_IDENTIFIER, true)
}

#[inline]
pub fn finish_pu_00_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Pu00Message<'a>>) {
  fbb.finish(root, Some(PU_00_MESSAGE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_pu_00_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Pu00Message<'a>>) {
  fbb.finish_size_prefixed(root, Some(PU_00_MESSAGE_IDENTIFIER));
}
