// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_LOCATION: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_LOCATION: i8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_LOCATION: [Location; 4] = [
  Location::Unknown,
  Location::Start,
  Location::Middle,
  Location::End,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Location(pub i8);
#[allow(non_upper_case_globals)]
impl Location {
  pub const Unknown: Self = Self(0);
  pub const Start: Self = Self(1);
  pub const Middle: Self = Self(2);
  pub const End: Self = Self(3);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Unknown,
    Self::Start,
    Self::Middle,
    Self::End,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Unknown => Some("Unknown"),
      Self::Start => Some("Start"),
      Self::Middle => Some("Middle"),
      Self::End => Some("End"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Location {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Location {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Location {
    type Output = Location;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Location {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Location {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Location {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_VALUE_UNION: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_VALUE_UNION: u8 = 10;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_VALUE_UNION: [ValueUnion; 11] = [
  ValueUnion::NONE,
  ValueUnion::Int8Array,
  ValueUnion::UInt8Array,
  ValueUnion::Int16Array,
  ValueUnion::UInt16Array,
  ValueUnion::Int32Array,
  ValueUnion::UInt32Array,
  ValueUnion::Int64Array,
  ValueUnion::UInt64Array,
  ValueUnion::DoubleArray,
  ValueUnion::FloatArray,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ValueUnion(pub u8);
#[allow(non_upper_case_globals)]
impl ValueUnion {
  pub const NONE: Self = Self(0);
  pub const Int8Array: Self = Self(1);
  pub const UInt8Array: Self = Self(2);
  pub const Int16Array: Self = Self(3);
  pub const UInt16Array: Self = Self(4);
  pub const Int32Array: Self = Self(5);
  pub const UInt32Array: Self = Self(6);
  pub const Int64Array: Self = Self(7);
  pub const UInt64Array: Self = Self(8);
  pub const DoubleArray: Self = Self(9);
  pub const FloatArray: Self = Self(10);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 10;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::Int8Array,
    Self::UInt8Array,
    Self::Int16Array,
    Self::UInt16Array,
    Self::Int32Array,
    Self::UInt32Array,
    Self::Int64Array,
    Self::UInt64Array,
    Self::DoubleArray,
    Self::FloatArray,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::Int8Array => Some("Int8Array"),
      Self::UInt8Array => Some("UInt8Array"),
      Self::Int16Array => Some("Int16Array"),
      Self::UInt16Array => Some("UInt16Array"),
      Self::Int32Array => Some("Int32Array"),
      Self::UInt32Array => Some("UInt32Array"),
      Self::Int64Array => Some("Int64Array"),
      Self::UInt64Array => Some("UInt64Array"),
      Self::DoubleArray => Some("DoubleArray"),
      Self::FloatArray => Some("FloatArray"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for ValueUnion {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for ValueUnion {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for ValueUnion {
    type Output = ValueUnion;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for ValueUnion {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for ValueUnion {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for ValueUnion {}
pub struct ValueUnionUnionTableOffset {}

pub enum Int8ArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Int8Array<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Int8Array<'a> {
  type Inner = Int8Array<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Int8Array<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Int8Array { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args Int8ArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Int8Array<'bldr>> {
    let mut builder = Int8ArrayBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> ::flatbuffers::Vector<'a, i8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i8>>>(Int8Array::VT_VALUE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Int8Array<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i8>>>("value", Self::VT_VALUE, true)?
     .finish();
    Ok(())
  }
}
pub struct Int8ArrayArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i8>>>,
}
impl<'a> Default for Int8ArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    Int8ArrayArgs {
      value: None, // required field
    }
  }
}

pub struct Int8ArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> Int8ArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Int8Array::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> Int8ArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    Int8ArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Int8Array<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Int8Array::VT_VALUE,"value");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Int8Array<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Int8Array");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum UInt8ArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct UInt8Array<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for UInt8Array<'a> {
  type Inner = UInt8Array<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> UInt8Array<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    UInt8Array { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args UInt8ArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<UInt8Array<'bldr>> {
    let mut builder = UInt8ArrayBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(UInt8Array::VT_VALUE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for UInt8Array<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("value", Self::VT_VALUE, true)?
     .finish();
    Ok(())
  }
}
pub struct UInt8ArrayArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for UInt8ArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    UInt8ArrayArgs {
      value: None, // required field
    }
  }
}

pub struct UInt8ArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UInt8ArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(UInt8Array::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> UInt8ArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    UInt8ArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<UInt8Array<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, UInt8Array::VT_VALUE,"value");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for UInt8Array<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("UInt8Array");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum Int16ArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Int16Array<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Int16Array<'a> {
  type Inner = Int16Array<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Int16Array<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Int16Array { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args Int16ArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Int16Array<'bldr>> {
    let mut builder = Int16ArrayBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> ::flatbuffers::Vector<'a, i16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i16>>>(Int16Array::VT_VALUE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Int16Array<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i16>>>("value", Self::VT_VALUE, true)?
     .finish();
    Ok(())
  }
}
pub struct Int16ArrayArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i16>>>,
}
impl<'a> Default for Int16ArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    Int16ArrayArgs {
      value: None, // required field
    }
  }
}

pub struct Int16ArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> Int16ArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i16>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Int16Array::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> Int16ArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    Int16ArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Int16Array<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Int16Array::VT_VALUE,"value");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Int16Array<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Int16Array");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum UInt16ArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct UInt16Array<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for UInt16Array<'a> {
  type Inner = UInt16Array<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> UInt16Array<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    UInt16Array { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args UInt16ArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<UInt16Array<'bldr>> {
    let mut builder = UInt16ArrayBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> ::flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u16>>>(UInt16Array::VT_VALUE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for UInt16Array<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u16>>>("value", Self::VT_VALUE, true)?
     .finish();
    Ok(())
  }
}
pub struct UInt16ArrayArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u16>>>,
}
impl<'a> Default for UInt16ArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    UInt16ArrayArgs {
      value: None, // required field
    }
  }
}

pub struct UInt16ArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UInt16ArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(UInt16Array::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> UInt16ArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    UInt16ArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<UInt16Array<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, UInt16Array::VT_VALUE,"value");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for UInt16Array<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("UInt16Array");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum Int32ArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Int32Array<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Int32Array<'a> {
  type Inner = Int32Array<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Int32Array<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Int32Array { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args Int32ArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Int32Array<'bldr>> {
    let mut builder = Int32ArrayBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> ::flatbuffers::Vector<'a, i32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i32>>>(Int32Array::VT_VALUE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Int32Array<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i32>>>("value", Self::VT_VALUE, true)?
     .finish();
    Ok(())
  }
}
pub struct Int32ArrayArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i32>>>,
}
impl<'a> Default for Int32ArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    Int32ArrayArgs {
      value: None, // required field
    }
  }
}

pub struct Int32ArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> Int32ArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Int32Array::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> Int32ArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    Int32ArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Int32Array<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Int32Array::VT_VALUE,"value");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Int32Array<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Int32Array");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum UInt32ArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct UInt32Array<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for UInt32Array<'a> {
  type Inner = UInt32Array<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> UInt32Array<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    UInt32Array { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args UInt32ArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<UInt32Array<'bldr>> {
    let mut builder = UInt32ArrayBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> ::flatbuffers::Vector<'a, u32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u32>>>(UInt32Array::VT_VALUE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for UInt32Array<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u32>>>("value", Self::VT_VALUE, true)?
     .finish();
    Ok(())
  }
}
pub struct UInt32ArrayArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u32>>>,
}
impl<'a> Default for UInt32ArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    UInt32ArrayArgs {
      value: None, // required field
    }
  }
}

pub struct UInt32ArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UInt32ArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(UInt32Array::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> UInt32ArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    UInt32ArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<UInt32Array<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, UInt32Array::VT_VALUE,"value");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for UInt32Array<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("UInt32Array");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum Int64ArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Int64Array<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Int64Array<'a> {
  type Inner = Int64Array<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Int64Array<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Int64Array { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args Int64ArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Int64Array<'bldr>> {
    let mut builder = Int64ArrayBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> ::flatbuffers::Vector<'a, i64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i64>>>(Int64Array::VT_VALUE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Int64Array<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i64>>>("value", Self::VT_VALUE, true)?
     .finish();
    Ok(())
  }
}
pub struct Int64ArrayArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i64>>>,
}
impl<'a> Default for Int64ArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    Int64ArrayArgs {
      value: None, // required field
    }
  }
}

pub struct Int64ArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> Int64ArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Int64Array::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> Int64ArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    Int64ArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Int64Array<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Int64Array::VT_VALUE,"value");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Int64Array<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Int64Array");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum UInt64ArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct UInt64Array<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for UInt64Array<'a> {
  type Inner = UInt64Array<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> UInt64Array<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    UInt64Array { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args UInt64ArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<UInt64Array<'bldr>> {
    let mut builder = UInt64ArrayBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> ::flatbuffers::Vector<'a, u64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u64>>>(UInt64Array::VT_VALUE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for UInt64Array<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u64>>>("value", Self::VT_VALUE, true)?
     .finish();
    Ok(())
  }
}
pub struct UInt64ArrayArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u64>>>,
}
impl<'a> Default for UInt64ArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    UInt64ArrayArgs {
      value: None, // required field
    }
  }
}

pub struct UInt64ArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UInt64ArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(UInt64Array::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> UInt64ArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    UInt64ArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<UInt64Array<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, UInt64Array::VT_VALUE,"value");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for UInt64Array<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("UInt64Array");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum DoubleArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DoubleArray<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DoubleArray<'a> {
  type Inner = DoubleArray<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DoubleArray<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DoubleArray { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DoubleArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DoubleArray<'bldr>> {
    let mut builder = DoubleArrayBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> ::flatbuffers::Vector<'a, f64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f64>>>(DoubleArray::VT_VALUE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for DoubleArray<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f64>>>("value", Self::VT_VALUE, true)?
     .finish();
    Ok(())
  }
}
pub struct DoubleArrayArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f64>>>,
}
impl<'a> Default for DoubleArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    DoubleArrayArgs {
      value: None, // required field
    }
  }
}

pub struct DoubleArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DoubleArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DoubleArray::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DoubleArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DoubleArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DoubleArray<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, DoubleArray::VT_VALUE,"value");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DoubleArray<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DoubleArray");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum FloatArrayOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FloatArray<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for FloatArray<'a> {
  type Inner = FloatArray<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> FloatArray<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    FloatArray { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FloatArrayArgs<'args>
  ) -> ::flatbuffers::WIPOffset<FloatArray<'bldr>> {
    let mut builder = FloatArrayBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> ::flatbuffers::Vector<'a, f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f32>>>(FloatArray::VT_VALUE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for FloatArray<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f32>>>("value", Self::VT_VALUE, true)?
     .finish();
    Ok(())
  }
}
pub struct FloatArrayArgs<'a> {
    pub value: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f32>>>,
}
impl<'a> Default for FloatArrayArgs<'a> {
  #[inline]
  fn default() -> Self {
    FloatArrayArgs {
      value: None, // required field
    }
  }
}

pub struct FloatArrayBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FloatArrayBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , f32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FloatArray::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FloatArrayBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FloatArrayBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<FloatArray<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, FloatArray::VT_VALUE,"value");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for FloatArray<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("FloatArray");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum se00_SampleEnvironmentDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct se00_SampleEnvironmentData<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for se00_SampleEnvironmentData<'a> {
  type Inner = se00_SampleEnvironmentData<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> se00_SampleEnvironmentData<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_CHANNEL: ::flatbuffers::VOffsetT = 6;
  pub const VT_PACKET_TIMESTAMP: ::flatbuffers::VOffsetT = 8;
  pub const VT_TIME_DELTA: ::flatbuffers::VOffsetT = 10;
  pub const VT_TIMESTAMP_LOCATION: ::flatbuffers::VOffsetT = 12;
  pub const VT_VALUES_TYPE: ::flatbuffers::VOffsetT = 14;
  pub const VT_VALUES: ::flatbuffers::VOffsetT = 16;
  pub const VT_TIMESTAMPS: ::flatbuffers::VOffsetT = 18;
  pub const VT_MESSAGE_COUNTER: ::flatbuffers::VOffsetT = 20;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    se00_SampleEnvironmentData { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args se00_SampleEnvironmentDataArgs<'args>
  ) -> ::flatbuffers::WIPOffset<se00_SampleEnvironmentData<'bldr>> {
    let mut builder = se00_SampleEnvironmentDataBuilder::new(_fbb);
    builder.add_message_counter(args.message_counter);
    builder.add_time_delta(args.time_delta);
    builder.add_packet_timestamp(args.packet_timestamp);
    if let Some(x) = args.timestamps { builder.add_timestamps(x); }
    if let Some(x) = args.values { builder.add_values(x); }
    builder.add_channel(args.channel);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_values_type(args.values_type);
    builder.add_timestamp_location(args.timestamp_location);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(se00_SampleEnvironmentData::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn channel(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(se00_SampleEnvironmentData::VT_CHANNEL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn packet_timestamp(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(se00_SampleEnvironmentData::VT_PACKET_TIMESTAMP, Some(0)).unwrap()}
  }
  #[inline]
  pub fn time_delta(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(se00_SampleEnvironmentData::VT_TIME_DELTA, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn timestamp_location(&self) -> Location {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Location>(se00_SampleEnvironmentData::VT_TIMESTAMP_LOCATION, Some(Location::Unknown)).unwrap()}
  }
  #[inline]
  pub fn values_type(&self) -> ValueUnion {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ValueUnion>(se00_SampleEnvironmentData::VT_VALUES_TYPE, Some(ValueUnion::NONE)).unwrap()}
  }
  #[inline]
  pub fn values(&self) -> ::flatbuffers::Table<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(se00_SampleEnvironmentData::VT_VALUES, None).unwrap()}
  }
  #[inline]
  pub fn timestamps(&self) -> Option<::flatbuffers::Vector<'a, i64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i64>>>(se00_SampleEnvironmentData::VT_TIMESTAMPS, None)}
  }
  #[inline]
  pub fn message_counter(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(se00_SampleEnvironmentData::VT_MESSAGE_COUNTER, Some(0)).unwrap()}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn values_as_int_8_array(&self) -> Option<Int8Array<'a>> {
    if self.values_type() == ValueUnion::Int8Array {
      let u = self.values();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { Int8Array::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn values_as_uint_8_array(&self) -> Option<UInt8Array<'a>> {
    if self.values_type() == ValueUnion::UInt8Array {
      let u = self.values();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { UInt8Array::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn values_as_int_16_array(&self) -> Option<Int16Array<'a>> {
    if self.values_type() == ValueUnion::Int16Array {
      let u = self.values();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { Int16Array::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn values_as_uint_16_array(&self) -> Option<UInt16Array<'a>> {
    if self.values_type() == ValueUnion::UInt16Array {
      let u = self.values();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { UInt16Array::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn values_as_int_32_array(&self) -> Option<Int32Array<'a>> {
    if self.values_type() == ValueUnion::Int32Array {
      let u = self.values();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { Int32Array::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn values_as_uint_32_array(&self) -> Option<UInt32Array<'a>> {
    if self.values_type() == ValueUnion::UInt32Array {
      let u = self.values();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { UInt32Array::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn values_as_int_64_array(&self) -> Option<Int64Array<'a>> {
    if self.values_type() == ValueUnion::Int64Array {
      let u = self.values();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { Int64Array::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn values_as_uint_64_array(&self) -> Option<UInt64Array<'a>> {
    if self.values_type() == ValueUnion::UInt64Array {
      let u = self.values();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { UInt64Array::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn values_as_double_array(&self) -> Option<DoubleArray<'a>> {
    if self.values_type() == ValueUnion::DoubleArray {
      let u = self.values();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { DoubleArray::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn values_as_float_array(&self) -> Option<FloatArray<'a>> {
    if self.values_type() == ValueUnion::FloatArray {
      let u = self.values();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { FloatArray::init_from_table(u) })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for se00_SampleEnvironmentData<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<i32>("channel", Self::VT_CHANNEL, false)?
     .visit_field::<i64>("packet_timestamp", Self::VT_PACKET_TIMESTAMP, false)?
     .visit_field::<f64>("time_delta", Self::VT_TIME_DELTA, false)?
     .visit_field::<Location>("timestamp_location", Self::VT_TIMESTAMP_LOCATION, false)?
     .visit_union::<ValueUnion, _>("values_type", Self::VT_VALUES_TYPE, "values", Self::VT_VALUES, true, |key, v, pos| {
        match key {
          ValueUnion::Int8Array => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Int8Array>>("ValueUnion::Int8Array", pos),
          ValueUnion::UInt8Array => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<UInt8Array>>("ValueUnion::UInt8Array", pos),
          ValueUnion::Int16Array => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Int16Array>>("ValueUnion::Int16Array", pos),
          ValueUnion::UInt16Array => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<UInt16Array>>("ValueUnion::UInt16Array", pos),
          ValueUnion::Int32Array => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Int32Array>>("ValueUnion::Int32Array", pos),
          ValueUnion::UInt32Array => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<UInt32Array>>("ValueUnion::UInt32Array", pos),
          ValueUnion::Int64Array => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Int64Array>>("ValueUnion::Int64Array", pos),
          ValueUnion::UInt64Array => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<UInt64Array>>("ValueUnion::UInt64Array", pos),
          ValueUnion::DoubleArray => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<DoubleArray>>("ValueUnion::DoubleArray", pos),
          ValueUnion::FloatArray => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<FloatArray>>("ValueUnion::FloatArray", pos),
          _ => Ok(()),
        }
     })?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i64>>>("timestamps", Self::VT_TIMESTAMPS, false)?
     .visit_field::<i64>("message_counter", Self::VT_MESSAGE_COUNTER, false)?
     .finish();
    Ok(())
  }
}
pub struct se00_SampleEnvironmentDataArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub channel: i32,
    pub packet_timestamp: i64,
    pub time_delta: f64,
    pub timestamp_location: Location,
    pub values_type: ValueUnion,
    pub values: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
    pub timestamps: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i64>>>,
    pub message_counter: i64,
}
impl<'a> Default for se00_SampleEnvironmentDataArgs<'a> {
  #[inline]
  fn default() -> Self {
    se00_SampleEnvironmentDataArgs {
      name: None, // required field
      channel: 0,
      packet_timestamp: 0,
      time_delta: 0.0,
      timestamp_location: Location::Unknown,
      values_type: ValueUnion::NONE,
      values: None, // required field
      timestamps: None,
      message_counter: 0,
    }
  }
}

pub struct se00_SampleEnvironmentDataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> se00_SampleEnvironmentDataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(se00_SampleEnvironmentData::VT_NAME, name);
  }
  #[inline]
  pub fn add_channel(&mut self, channel: i32) {
    self.fbb_.push_slot::<i32>(se00_SampleEnvironmentData::VT_CHANNEL, channel, 0);
  }
  #[inline]
  pub fn add_packet_timestamp(&mut self, packet_timestamp: i64) {
    self.fbb_.push_slot::<i64>(se00_SampleEnvironmentData::VT_PACKET_TIMESTAMP, packet_timestamp, 0);
  }
  #[inline]
  pub fn add_time_delta(&mut self, time_delta: f64) {
    self.fbb_.push_slot::<f64>(se00_SampleEnvironmentData::VT_TIME_DELTA, time_delta, 0.0);
  }
  #[inline]
  pub fn add_timestamp_location(&mut self, timestamp_location: Location) {
    self.fbb_.push_slot::<Location>(se00_SampleEnvironmentData::VT_TIMESTAMP_LOCATION, timestamp_location, Location::Unknown);
  }
  #[inline]
  pub fn add_values_type(&mut self, values_type: ValueUnion) {
    self.fbb_.push_slot::<ValueUnion>(se00_SampleEnvironmentData::VT_VALUES_TYPE, values_type, ValueUnion::NONE);
  }
  #[inline]
  pub fn add_values(&mut self, values: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(se00_SampleEnvironmentData::VT_VALUES, values);
  }
  #[inline]
  pub fn add_timestamps(&mut self, timestamps: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(se00_SampleEnvironmentData::VT_TIMESTAMPS, timestamps);
  }
  #[inline]
  pub fn add_message_counter(&mut self, message_counter: i64) {
    self.fbb_.push_slot::<i64>(se00_SampleEnvironmentData::VT_MESSAGE_COUNTER, message_counter, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> se00_SampleEnvironmentDataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    se00_SampleEnvironmentDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<se00_SampleEnvironmentData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, se00_SampleEnvironmentData::VT_NAME,"name");
    self.fbb_.required(o, se00_SampleEnvironmentData::VT_VALUES,"values");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for se00_SampleEnvironmentData<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("se00_SampleEnvironmentData");
      ds.field("name", &self.name());
      ds.field("channel", &self.channel());
      ds.field("packet_timestamp", &self.packet_timestamp());
      ds.field("time_delta", &self.time_delta());
      ds.field("timestamp_location", &self.timestamp_location());
      ds.field("values_type", &self.values_type());
      match self.values_type() {
        ValueUnion::Int8Array => {
          if let Some(x) = self.values_as_int_8_array() {
            ds.field("values", &x)
          } else {
            ds.field("values", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        ValueUnion::UInt8Array => {
          if let Some(x) = self.values_as_uint_8_array() {
            ds.field("values", &x)
          } else {
            ds.field("values", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        ValueUnion::Int16Array => {
          if let Some(x) = self.values_as_int_16_array() {
            ds.field("values", &x)
          } else {
            ds.field("values", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        ValueUnion::UInt16Array => {
          if let Some(x) = self.values_as_uint_16_array() {
            ds.field("values", &x)
          } else {
            ds.field("values", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        ValueUnion::Int32Array => {
          if let Some(x) = self.values_as_int_32_array() {
            ds.field("values", &x)
          } else {
            ds.field("values", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        ValueUnion::UInt32Array => {
          if let Some(x) = self.values_as_uint_32_array() {
            ds.field("values", &x)
          } else {
            ds.field("values", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        ValueUnion::Int64Array => {
          if let Some(x) = self.values_as_int_64_array() {
            ds.field("values", &x)
          } else {
            ds.field("values", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        ValueUnion::UInt64Array => {
          if let Some(x) = self.values_as_uint_64_array() {
            ds.field("values", &x)
          } else {
            ds.field("values", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        ValueUnion::DoubleArray => {
          if let Some(x) = self.values_as_double_array() {
            ds.field("values", &x)
          } else {
            ds.field("values", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        ValueUnion::FloatArray => {
          if let Some(x) = self.values_as_float_array() {
            ds.field("values", &x)
          } else {
            ds.field("values", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("values", &x)
        },
      };
      ds.field("timestamps", &self.timestamps());
      ds.field("message_counter", &self.message_counter());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `se00_SampleEnvironmentData`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_se_00_sample_environment_data_unchecked`.
pub fn root_as_se_00_sample_environment_data(buf: &[u8]) -> Result<se00_SampleEnvironmentData<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<se00_SampleEnvironmentData>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `se00_SampleEnvironmentData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_se_00_sample_environment_data_unchecked`.
pub fn size_prefixed_root_as_se_00_sample_environment_data(buf: &[u8]) -> Result<se00_SampleEnvironmentData<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<se00_SampleEnvironmentData>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `se00_SampleEnvironmentData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_se_00_sample_environment_data_unchecked`.
pub fn root_as_se_00_sample_environment_data_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<se00_SampleEnvironmentData<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<se00_SampleEnvironmentData<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `se00_SampleEnvironmentData` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_se_00_sample_environment_data_unchecked`.
pub fn size_prefixed_root_as_se_00_sample_environment_data_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<se00_SampleEnvironmentData<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<se00_SampleEnvironmentData<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a se00_SampleEnvironmentData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `se00_SampleEnvironmentData`.
pub unsafe fn root_as_se_00_sample_environment_data_unchecked(buf: &[u8]) -> se00_SampleEnvironmentData<'_> {
  unsafe { ::flatbuffers::root_unchecked::<se00_SampleEnvironmentData>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed se00_SampleEnvironmentData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `se00_SampleEnvironmentData`.
pub unsafe fn size_prefixed_root_as_se_00_sample_environment_data_unchecked(buf: &[u8]) -> se00_SampleEnvironmentData<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<se00_SampleEnvironmentData>(buf) }
}
pub const SE_00_SAMPLE_ENVIRONMENT_DATA_IDENTIFIER: &str = "se00";

#[inline]
pub fn se_00_sample_environment_data_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, SE_00_SAMPLE_ENVIRONMENT_DATA_IDENTIFIER, false)
}

#[inline]
pub fn se_00_sample_environment_data_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, SE_00_SAMPLE_ENVIRONMENT_DATA_IDENTIFIER, true)
}

#[inline]
pub fn finish_se_00_sample_environment_data_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<se00_SampleEnvironmentData<'a>>) {
  fbb.finish(root, Some(SE_00_SAMPLE_ENVIRONMENT_DATA_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_se_00_sample_environment_data_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<se00_SampleEnvironmentData<'a>>) {
  fbb.finish_size_prefixed(root, Some(SE_00_SAMPLE_ENVIRONMENT_DATA_IDENTIFIER));
}
