// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

pub enum UnitsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Units<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Units<'a> {
  type Inner = Units<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Units<'a> {
  pub const VT_SOURCE_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_TIMESTAMP: ::flatbuffers::VOffsetT = 6;
  pub const VT_UNITS: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Units { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args UnitsArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Units<'bldr>> {
    let mut builder = UnitsBuilder::new(_fbb);
    builder.add_timestamp(args.timestamp);
    if let Some(x) = args.units { builder.add_units(x); }
    if let Some(x) = args.source_name { builder.add_source_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn source_name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Units::VT_SOURCE_NAME, None).unwrap()}
  }
  #[inline]
  pub fn timestamp(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Units::VT_TIMESTAMP, Some(0)).unwrap()}
  }
  #[inline]
  pub fn units(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Units::VT_UNITS, None)}
  }
}

impl ::flatbuffers::Verifiable for Units<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("source_name", Self::VT_SOURCE_NAME, true)?
     .visit_field::<i64>("timestamp", Self::VT_TIMESTAMP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("units", Self::VT_UNITS, false)?
     .finish();
    Ok(())
  }
}
pub struct UnitsArgs<'a> {
    pub source_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub timestamp: i64,
    pub units: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for UnitsArgs<'a> {
  #[inline]
  fn default() -> Self {
    UnitsArgs {
      source_name: None, // required field
      timestamp: 0,
      units: None,
    }
  }
}

pub struct UnitsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UnitsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_source_name(&mut self, source_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Units::VT_SOURCE_NAME, source_name);
  }
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: i64) {
    self.fbb_.push_slot::<i64>(Units::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn add_units(&mut self, units: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Units::VT_UNITS, units);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> UnitsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    UnitsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Units<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Units::VT_SOURCE_NAME,"source_name");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Units<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Units");
      ds.field("source_name", &self.source_name());
      ds.field("timestamp", &self.timestamp());
      ds.field("units", &self.units());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Units`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_units_unchecked`.
pub fn root_as_units(buf: &[u8]) -> Result<Units<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Units>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Units` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_units_unchecked`.
pub fn size_prefixed_root_as_units(buf: &[u8]) -> Result<Units<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Units>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Units` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_units_unchecked`.
pub fn root_as_units_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Units<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Units<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Units` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_units_unchecked`.
pub fn size_prefixed_root_as_units_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Units<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Units<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Units and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Units`.
pub unsafe fn root_as_units_unchecked(buf: &[u8]) -> Units<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Units>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Units and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Units`.
pub unsafe fn size_prefixed_root_as_units_unchecked(buf: &[u8]) -> Units<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Units>(buf) }
}
pub const UNITS_IDENTIFIER: &str = "un00";

#[inline]
pub fn units_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, UNITS_IDENTIFIER, false)
}

#[inline]
pub fn units_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, UNITS_IDENTIFIER, true)
}

#[inline]
pub fn finish_units_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Units<'a>>) {
  fbb.finish(root, Some(UNITS_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_units_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Units<'a>>) {
  fbb.finish_size_prefixed(root, Some(UNITS_IDENTIFIER));
}
