// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

pub enum VetoesOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Vetoes<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Vetoes<'a> {
  type Inner = Vetoes<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Vetoes<'a> {
  pub const VT_TIMESTAMP: ::flatbuffers::VOffsetT = 4;
  pub const VT_VETOES: ::flatbuffers::VOffsetT = 6;
  pub const VT_VETO_NAMES: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Vetoes { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args VetoesArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Vetoes<'bldr>> {
    let mut builder = VetoesBuilder::new(_fbb);
    builder.add_timestamp(args.timestamp);
    if let Some(x) = args.veto_names { builder.add_veto_names(x); }
    builder.add_vetoes(args.vetoes);
    builder.finish()
  }


  #[inline]
  pub fn timestamp(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Vetoes::VT_TIMESTAMP, Some(0)).unwrap()}
  }
  #[inline]
  pub fn vetoes(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Vetoes::VT_VETOES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn veto_names(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(Vetoes::VT_VETO_NAMES, None)}
  }
}

impl ::flatbuffers::Verifiable for Vetoes<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<i64>("timestamp", Self::VT_TIMESTAMP, false)?
     .visit_field::<u32>("vetoes", Self::VT_VETOES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("veto_names", Self::VT_VETO_NAMES, false)?
     .finish();
    Ok(())
  }
}
pub struct VetoesArgs<'a> {
    pub timestamp: i64,
    pub vetoes: u32,
    pub veto_names: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
}
impl<'a> Default for VetoesArgs<'a> {
  #[inline]
  fn default() -> Self {
    VetoesArgs {
      timestamp: 0,
      vetoes: 0,
      veto_names: None,
    }
  }
}

pub struct VetoesBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> VetoesBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: i64) {
    self.fbb_.push_slot::<i64>(Vetoes::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn add_vetoes(&mut self, vetoes: u32) {
    self.fbb_.push_slot::<u32>(Vetoes::VT_VETOES, vetoes, 0);
  }
  #[inline]
  pub fn add_veto_names(&mut self, veto_names: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Vetoes::VT_VETO_NAMES, veto_names);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> VetoesBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    VetoesBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Vetoes<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Vetoes<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Vetoes");
      ds.field("timestamp", &self.timestamp());
      ds.field("vetoes", &self.vetoes());
      ds.field("veto_names", &self.veto_names());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Vetoes`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_vetoes_unchecked`.
pub fn root_as_vetoes(buf: &[u8]) -> Result<Vetoes<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Vetoes>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Vetoes` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_vetoes_unchecked`.
pub fn size_prefixed_root_as_vetoes(buf: &[u8]) -> Result<Vetoes<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Vetoes>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Vetoes` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_vetoes_unchecked`.
pub fn root_as_vetoes_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Vetoes<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Vetoes<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Vetoes` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_vetoes_unchecked`.
pub fn size_prefixed_root_as_vetoes_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Vetoes<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Vetoes<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Vetoes and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Vetoes`.
pub unsafe fn root_as_vetoes_unchecked(buf: &[u8]) -> Vetoes<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Vetoes>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Vetoes and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Vetoes`.
pub unsafe fn size_prefixed_root_as_vetoes_unchecked(buf: &[u8]) -> Vetoes<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Vetoes>(buf) }
}
pub const VETOES_IDENTIFIER: &str = "vc00";

#[inline]
pub fn vetoes_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, VETOES_IDENTIFIER, false)
}

#[inline]
pub fn vetoes_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, VETOES_IDENTIFIER, true)
}

#[inline]
pub fn finish_vetoes_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Vetoes<'a>>) {
  fbb.finish(root, Some(VETOES_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_vetoes_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Vetoes<'a>>) {
  fbb.finish_size_prefixed(root, Some(VETOES_IDENTIFIER));
}
