// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

pub enum FinishedWritingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FinishedWriting<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for FinishedWriting<'a> {
  type Inner = FinishedWriting<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> FinishedWriting<'a> {
  pub const VT_SERVICE_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_JOB_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_ERROR_ENCOUNTERED: ::flatbuffers::VOffsetT = 8;
  pub const VT_FILE_NAME: ::flatbuffers::VOffsetT = 10;
  pub const VT_METADATA: ::flatbuffers::VOffsetT = 12;
  pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    FinishedWriting { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FinishedWritingArgs<'args>
  ) -> ::flatbuffers::WIPOffset<FinishedWriting<'bldr>> {
    let mut builder = FinishedWritingBuilder::new(_fbb);
    if let Some(x) = args.message { builder.add_message(x); }
    if let Some(x) = args.metadata { builder.add_metadata(x); }
    if let Some(x) = args.file_name { builder.add_file_name(x); }
    if let Some(x) = args.job_id { builder.add_job_id(x); }
    if let Some(x) = args.service_id { builder.add_service_id(x); }
    builder.add_error_encountered(args.error_encountered);
    builder.finish()
  }


  #[inline]
  pub fn service_id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(FinishedWriting::VT_SERVICE_ID, None).unwrap()}
  }
  #[inline]
  pub fn job_id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(FinishedWriting::VT_JOB_ID, None).unwrap()}
  }
  #[inline]
  pub fn error_encountered(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(FinishedWriting::VT_ERROR_ENCOUNTERED, Some(false)).unwrap()}
  }
  #[inline]
  pub fn file_name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(FinishedWriting::VT_FILE_NAME, None).unwrap()}
  }
  #[inline]
  pub fn metadata(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(FinishedWriting::VT_METADATA, None)}
  }
  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(FinishedWriting::VT_MESSAGE, None)}
  }
}

impl ::flatbuffers::Verifiable for FinishedWriting<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("service_id", Self::VT_SERVICE_ID, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("job_id", Self::VT_JOB_ID, true)?
     .visit_field::<bool>("error_encountered", Self::VT_ERROR_ENCOUNTERED, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("file_name", Self::VT_FILE_NAME, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("metadata", Self::VT_METADATA, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .finish();
    Ok(())
  }
}
pub struct FinishedWritingArgs<'a> {
    pub service_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub job_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub error_encountered: bool,
    pub file_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub metadata: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub message: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for FinishedWritingArgs<'a> {
  #[inline]
  fn default() -> Self {
    FinishedWritingArgs {
      service_id: None, // required field
      job_id: None, // required field
      error_encountered: false,
      file_name: None, // required field
      metadata: None,
      message: None,
    }
  }
}

pub struct FinishedWritingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FinishedWritingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_service_id(&mut self, service_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FinishedWriting::VT_SERVICE_ID, service_id);
  }
  #[inline]
  pub fn add_job_id(&mut self, job_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FinishedWriting::VT_JOB_ID, job_id);
  }
  #[inline]
  pub fn add_error_encountered(&mut self, error_encountered: bool) {
    self.fbb_.push_slot::<bool>(FinishedWriting::VT_ERROR_ENCOUNTERED, error_encountered, false);
  }
  #[inline]
  pub fn add_file_name(&mut self, file_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FinishedWriting::VT_FILE_NAME, file_name);
  }
  #[inline]
  pub fn add_metadata(&mut self, metadata: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FinishedWriting::VT_METADATA, metadata);
  }
  #[inline]
  pub fn add_message(&mut self, message: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FinishedWriting::VT_MESSAGE, message);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FinishedWritingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FinishedWritingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<FinishedWriting<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, FinishedWriting::VT_SERVICE_ID,"service_id");
    self.fbb_.required(o, FinishedWriting::VT_JOB_ID,"job_id");
    self.fbb_.required(o, FinishedWriting::VT_FILE_NAME,"file_name");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for FinishedWriting<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("FinishedWriting");
      ds.field("service_id", &self.service_id());
      ds.field("job_id", &self.job_id());
      ds.field("error_encountered", &self.error_encountered());
      ds.field("file_name", &self.file_name());
      ds.field("metadata", &self.metadata());
      ds.field("message", &self.message());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `FinishedWriting`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_finished_writing_unchecked`.
pub fn root_as_finished_writing(buf: &[u8]) -> Result<FinishedWriting<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<FinishedWriting>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `FinishedWriting` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_finished_writing_unchecked`.
pub fn size_prefixed_root_as_finished_writing(buf: &[u8]) -> Result<FinishedWriting<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<FinishedWriting>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `FinishedWriting` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_finished_writing_unchecked`.
pub fn root_as_finished_writing_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<FinishedWriting<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<FinishedWriting<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `FinishedWriting` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_finished_writing_unchecked`.
pub fn size_prefixed_root_as_finished_writing_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<FinishedWriting<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<FinishedWriting<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a FinishedWriting and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `FinishedWriting`.
pub unsafe fn root_as_finished_writing_unchecked(buf: &[u8]) -> FinishedWriting<'_> {
  unsafe { ::flatbuffers::root_unchecked::<FinishedWriting>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed FinishedWriting and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `FinishedWriting`.
pub unsafe fn size_prefixed_root_as_finished_writing_unchecked(buf: &[u8]) -> FinishedWriting<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<FinishedWriting>(buf) }
}
pub const FINISHED_WRITING_IDENTIFIER: &str = "wrdn";

#[inline]
pub fn finished_writing_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, FINISHED_WRITING_IDENTIFIER, false)
}

#[inline]
pub fn finished_writing_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, FINISHED_WRITING_IDENTIFIER, true)
}

#[inline]
pub fn finish_finished_writing_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<FinishedWriting<'a>>) {
  fbb.finish(root, Some(FINISHED_WRITING_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_finished_writing_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<FinishedWriting<'a>>) {
  fbb.finish_size_prefixed(root, Some(FINISHED_WRITING_IDENTIFIER));
}
