// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

pub enum StatusOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Status<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Status<'a> {
  type Inner = Status<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Status<'a> {
  pub const VT_SOFTWARE_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_SOFTWARE_VERSION: ::flatbuffers::VOffsetT = 6;
  pub const VT_SERVICE_ID: ::flatbuffers::VOffsetT = 8;
  pub const VT_HOST_NAME: ::flatbuffers::VOffsetT = 10;
  pub const VT_PROCESS_ID: ::flatbuffers::VOffsetT = 12;
  pub const VT_UPDATE_INTERVAL: ::flatbuffers::VOffsetT = 14;
  pub const VT_STATUS_JSON: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Status { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args StatusArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Status<'bldr>> {
    let mut builder = StatusBuilder::new(_fbb);
    if let Some(x) = args.status_json { builder.add_status_json(x); }
    builder.add_update_interval(args.update_interval);
    builder.add_process_id(args.process_id);
    if let Some(x) = args.host_name { builder.add_host_name(x); }
    if let Some(x) = args.service_id { builder.add_service_id(x); }
    if let Some(x) = args.software_version { builder.add_software_version(x); }
    if let Some(x) = args.software_name { builder.add_software_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn software_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Status::VT_SOFTWARE_NAME, None)}
  }
  #[inline]
  pub fn software_version(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Status::VT_SOFTWARE_VERSION, None)}
  }
  #[inline]
  pub fn service_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Status::VT_SERVICE_ID, None)}
  }
  #[inline]
  pub fn host_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Status::VT_HOST_NAME, None)}
  }
  #[inline]
  pub fn process_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Status::VT_PROCESS_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn update_interval(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Status::VT_UPDATE_INTERVAL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn status_json(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Status::VT_STATUS_JSON, None)}
  }
}

impl ::flatbuffers::Verifiable for Status<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("software_name", Self::VT_SOFTWARE_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("software_version", Self::VT_SOFTWARE_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("service_id", Self::VT_SERVICE_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("host_name", Self::VT_HOST_NAME, false)?
     .visit_field::<u32>("process_id", Self::VT_PROCESS_ID, false)?
     .visit_field::<u32>("update_interval", Self::VT_UPDATE_INTERVAL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("status_json", Self::VT_STATUS_JSON, false)?
     .finish();
    Ok(())
  }
}
pub struct StatusArgs<'a> {
    pub software_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub software_version: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub service_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub host_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub process_id: u32,
    pub update_interval: u32,
    pub status_json: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for StatusArgs<'a> {
  #[inline]
  fn default() -> Self {
    StatusArgs {
      software_name: None,
      software_version: None,
      service_id: None,
      host_name: None,
      process_id: 0,
      update_interval: 0,
      status_json: None,
    }
  }
}

pub struct StatusBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> StatusBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_software_name(&mut self, software_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Status::VT_SOFTWARE_NAME, software_name);
  }
  #[inline]
  pub fn add_software_version(&mut self, software_version: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Status::VT_SOFTWARE_VERSION, software_version);
  }
  #[inline]
  pub fn add_service_id(&mut self, service_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Status::VT_SERVICE_ID, service_id);
  }
  #[inline]
  pub fn add_host_name(&mut self, host_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Status::VT_HOST_NAME, host_name);
  }
  #[inline]
  pub fn add_process_id(&mut self, process_id: u32) {
    self.fbb_.push_slot::<u32>(Status::VT_PROCESS_ID, process_id, 0);
  }
  #[inline]
  pub fn add_update_interval(&mut self, update_interval: u32) {
    self.fbb_.push_slot::<u32>(Status::VT_UPDATE_INTERVAL, update_interval, 0);
  }
  #[inline]
  pub fn add_status_json(&mut self, status_json: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Status::VT_STATUS_JSON, status_json);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> StatusBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    StatusBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Status<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Status<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Status");
      ds.field("software_name", &self.software_name());
      ds.field("software_version", &self.software_version());
      ds.field("service_id", &self.service_id());
      ds.field("host_name", &self.host_name());
      ds.field("process_id", &self.process_id());
      ds.field("update_interval", &self.update_interval());
      ds.field("status_json", &self.status_json());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Status`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_status_unchecked`.
pub fn root_as_status(buf: &[u8]) -> Result<Status<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Status>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Status` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_status_unchecked`.
pub fn size_prefixed_root_as_status(buf: &[u8]) -> Result<Status<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Status>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Status` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_status_unchecked`.
pub fn root_as_status_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Status<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Status<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Status` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_status_unchecked`.
pub fn size_prefixed_root_as_status_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Status<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Status<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Status and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Status`.
pub unsafe fn root_as_status_unchecked(buf: &[u8]) -> Status<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Status>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Status and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Status`.
pub unsafe fn size_prefixed_root_as_status_unchecked(buf: &[u8]) -> Status<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Status>(buf) }
}
pub const STATUS_IDENTIFIER: &str = "x5f2";

#[inline]
pub fn status_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, STATUS_IDENTIFIER, false)
}

#[inline]
pub fn status_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, STATUS_IDENTIFIER, true)
}

#[inline]
pub fn finish_status_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Status<'a>>) {
  fbb.finish(root, Some(STATUS_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_status_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Status<'a>>) {
  fbb.finish_size_prefixed(root, Some(STATUS_IDENTIFIER));
}
